n_support: 8
beam_width: 32
n_restarts: 8
max_len: 32
numeric_head: False
equivalence_pruning: True
pointwise_close_criterion: 0.95
pointwise_close_accuracy_rtol: 0.05
pointwise_close_accuracy_atol: 0.001
r2_close_criterion: 0.95
refiner_p0_noise: 'uniform'
refiner_p0_noise_kwargs: {'low': -5, 'high': 5}
device: cuda