"""Training orchestration logic for Flash-ANSR models.

This module provides the `Trainer` class, which encapsulates the full
training/validation loop as well as utilities for configuration driven
initialisation and experiment logging.
"""

import copy
import os
from typing import Any, Literal

import torch

from flash_ansr.utils.weights import load_weights

from torch.optim.lr_scheduler import LRScheduler
from torch import nn

from tqdm import tqdm

from flash_ansr.model import FlashANSRModel
from flash_ansr.data import FlashANSRDataset
from flash_ansr.data.collate import mask_float_targets
from flash_ansr.utils.config_io import load_config, save_config, unfold_config
from flash_ansr.utils.paths import substitute_root_path
from flash_ansr.train.optimizers import get_optimizer
from flash_ansr.train.schedules import pw_linear_schedule

# ---------------------------------------------------------------------------
# Compatibility patches
# ---------------------------------------------------------------------------

# Pydantic 2.x emits UnsupportedFieldAttributeWarning when libraries such as
# wandb still pass ``repr``/``frozen`` to ``Field``. Strip these keywords before
# wandb imports its autogenerated models to keep logs clean without suppressing
# warnings globally.
try:  # pragma: no cover - defensive import guard
    import pydantic
    from pydantic import Field as _ORIGINAL_PYDANTIC_FIELD
    from pydantic import fields as _pydantic_fields
except Exception:  # noqa: BLE001 - best-effort shim; fall back silently
    _ORIGINAL_PYDANTIC_FIELD = None  # type: ignore[assignment]
else:
    assert _ORIGINAL_PYDANTIC_FIELD is not None

    def _field_without_unused_attrs(*args: Any, **kwargs: Any) -> Any:
        kwargs.pop('repr', None)
        kwargs.pop('frozen', None)
        return _ORIGINAL_PYDANTIC_FIELD(*args, **kwargs)

    pydantic.Field = _field_without_unused_attrs  # type: ignore[attr-defined]

    _orig_fieldinfo_init = _pydantic_fields.FieldInfo.__init__

    def _fieldinfo_init_without_unused_attrs(self: Any, *args: Any, **kwargs: Any) -> None:
        kwargs.pop('repr', None)
        kwargs.pop('frozen', None)
        _orig_fieldinfo_init(self, *args, **kwargs)

    _pydantic_fields.FieldInfo.__init__ = _fieldinfo_init_without_unused_attrs  # type: ignore[method-assign]

import wandb


def _enable_tf32_precision() -> None:
    if not torch.cuda.is_available():
        return

    try:
        device_capabilities = [torch.cuda.get_device_capability(i) for i in range(torch.cuda.device_count())]
    except RuntimeError:
        # CUDA context is not ready; defer enabling.
        return

    if not any(major >= 8 for major, _ in device_capabilities):
        # TF32 support starts with Ampere (compute capability 8.0).
        return

    matmul_backend = getattr(torch.backends.cuda, 'matmul', None)
    conv_backend = getattr(torch.backends.cudnn, 'conv', None)

    try:
        if matmul_backend is not None and hasattr(matmul_backend, 'fp32_precision'):
            matmul_backend.fp32_precision = 'tf32'
        if conv_backend is not None and hasattr(conv_backend, 'fp32_precision'):
            conv_backend.fp32_precision = 'tf32'
    except AttributeError:
        # Older Torch builds without the new API still honour the legacy helper.
        torch.set_float32_matmul_precision('high')


_enable_tf32_precision()


TASK_SEGMENT_NAMES = {0: "expression", 1: "complexity", 2: "predict_y", 3: "predict_constants",
                      4: "predict_residual"}


def _z_loss(flat_logits: torch.Tensor, valid_labels: torch.Tensor) -> torch.Tensor:
    """Mean squared log-partition (PaLM z-loss) over the supervised positions, in fp32.

    Cross-entropy is shift-invariant, so a shared logit offset is loss-flat and Adam's
    sign-persistence slides along it without bound (the T4 byte-row runaway, 2026-09-01:
    byte-position max logit drifted to -110 and the head carried 94% of the gradient
    energy). log^2 Z is the restoring force on exactly that direction. Computed in fp32:
    at the offsets this loss exists to shrink, bf16 logsumexp is the wrong tool."""
    log_z = torch.logsumexp(flat_logits[valid_labels].float(), dim=-1)
    return (log_z * log_z).mean()


def _per_task_ce(logits: torch.Tensor, labels: torch.Tensor, segments: torch.Tensor,
                 ignore_index: int) -> "dict[str, tuple[float, int]]":
    """CE sum and token count per task segment, over the SUPERVISED labels only (the
    task/prompt/float masks have already written ignore_index into the labels, so each
    segment's mean is the loss on exactly its trained tokens). Shifted-label discipline
    like the masks; metric-only (caller detaches)."""
    seg = segments[..., 1:]
    if seg.shape[-1] > labels.shape[-1]:
        seg = seg[..., :labels.shape[-1]]
    elif seg.shape[-1] < labels.shape[-1]:
        labels = labels[..., :seg.shape[-1]]
    flat_logits = logits[:, :-1].reshape(-1, logits.shape[-1])[:labels.numel()]
    flat_labels = labels.reshape(-1)
    flat_segments = seg.reshape(-1)
    valid = flat_labels != ignore_index
    parts: dict[str, tuple[float, int]] = {}
    if valid.any():
        ce = nn.functional.cross_entropy(flat_logits[valid], flat_labels[valid], reduction="none")
        valid_segments = flat_segments[valid]
        for segment_id, name in TASK_SEGMENT_NAMES.items():
            member = valid_segments == segment_id
            if member.any():
                parts[name] = (float(ce[member].sum()), int(member.sum()))
    return parts


def _ce_split_metrics(batch: "dict[str, Any]", logits: torch.Tensor,
                      ignore_index: int) -> "dict[str, tuple[float, int]]":
    """Fine-grained CE curves: task segments crossed with per-instance conditioning
    circumstances (owner request 2026-08-24 -- the prior mixes many tasks in many
    circumstances, and each combination gets its own wandb curve under ``ce_split/``).

    Splits that exist by construction: expression x data-conditioning (CFG mask),
    expression x complexity-block presence, complexity bytes x data-conditioning, and
    predict_y x variant (conditional b / unconditional a). predict_y x data-dropout does
    not occur -- dropout instances carry no predict_y block by design. Keys are emitted
    only for combinations present in the batch; the flat ``*_ce_*`` totals are untouched.

    ``expression/anchor`` is the cross-arm COMMON GROUND: expression CE restricted to
    instances with no expression-informing block (complexity absent, predict_y absent
    or conditional, no mask flag), emitted in base-shaped runs too (where it equals
    the expression CE), so main-task ability is comparable across arms with different
    task mixes; partial instances (unflagged placeholders) are excluded too. The
    promptable-mask feature adds ``expression/mask_all|mask_fittable|unmasked|partial``,
    ``predict_y/masked_ctx|unmasked_ctx`` and ``constants/after_flagged|partial``.
    """
    segments = batch.get('task_segments')
    labels = batch.get('labels')
    if labels is None or not isinstance(labels, torch.Tensor):
        return {}
    if segments is None:
        # A base-shaped run (no task blocks): every position is expression. Splits are
        # still emitted so the ANCHOR key below exists in every arm -- it is the common
        # ground the ablation comparisons read (owner request 2026-08-24).
        seg = torch.zeros_like(labels)
    else:
        seg = segments[..., 1:]
        if seg.shape[-1] > labels.shape[-1]:
            seg = seg[..., :labels.shape[-1]]
        elif seg.shape[-1] < labels.shape[-1]:
            labels = labels[..., :seg.shape[-1]]
    n_rows, n_positions = labels.shape
    flat_ce = nn.functional.cross_entropy(
        logits[:, :-1].reshape(-1, logits.shape[-1])[:labels.numel()],
        labels.reshape(-1), reduction='none', ignore_index=ignore_index)
    ce = flat_ce.reshape(n_rows, n_positions)
    valid = labels != ignore_index

    def rows(values: "list[bool]") -> torch.Tensor:
        return torch.tensor(values, dtype=torch.bool, device=labels.device)

    splits: "list[tuple[str, int, torch.Tensor]]" = []
    condition_mask = batch.get('condition_mask')
    if condition_mask is not None:
        conditioned = (condition_mask.to(device=labels.device, dtype=torch.bool)
                       if isinstance(condition_mask, torch.Tensor) else rows([bool(v) for v in condition_mask]))
        splits.append(("expression/data_cond", 0, conditioned))
        splits.append(("expression/data_uncond", 0, ~conditioned))
    complexity_variant = batch.get('complexity_variant')
    if complexity_variant is not None:
        present = rows([v is not None for v in complexity_variant])
        splits.append(("expression/complexity_present", 0, present))
        splits.append(("expression/complexity_absent", 0, ~present))
        if condition_mask is not None:
            splits.append(("complexity/data_cond", 1, conditioned))
            splits.append(("complexity/data_uncond", 1, ~conditioned))
        hypothesized = rows([v == "hypothesis" for v in complexity_variant])
        prompted = rows([v == "float" for v in complexity_variant])
        splits.append(("complexity/hypothesized", 1, hypothesized))
        splits.append(("complexity/prompted", 1, prompted))
    predict_y = batch.get('predict_y')

    # THE ANCHOR (owner request 2026-08-24): expression CE on instances shaped exactly
    # like the base task -- nothing that precedes the expression informs it (complexity
    # block absent; predict_y and predict_residual absent or in the CONDITIONAL
    # position, which follows the expression and cannot reach its logits under causal
    # masking). In a base arm every instance qualifies, so the anchor equals the plain expression CE; across arms it
    # is the like-for-like main-task curve. It does NOT equalize the data distribution:
    # arms trained under different noise configs still predict the expression from
    # different data -- hold the noise setting constant across arms for a clean read.
    complexity_variant_list = batch.get('complexity_variant')
    mask_mode_list = batch.get('mask_mode')
    n_placeholders_list = batch.get('n_placeholders')
    predict_residual = batch.get('predict_residual')
    anchor = rows([
        (complexity_variant_list is None or complexity_variant_list[i] is None)
        and (predict_y is None or predict_y[i] is None or bool(predict_y[i]["conditional"]))
        and (predict_residual is None or predict_residual[i] is None
             or bool(predict_residual[i]["conditional"]))
        and (mask_mode_list is None or mask_mode_list[i] is None)
        and (n_placeholders_list is None or int(n_placeholders_list[i]) == 0)
        for i in range(n_rows)
    ])
    splits.append(("expression/anchor", 0, anchor))

    if mask_mode_list is not None:
        # The promptable-mask circumstances (owner: split metrics for each case): the
        # expression under each target format, and predict_y under a masked vs
        # unmasked expression context (a masked context withholds the constants the
        # conditional variant would otherwise read off the expression).
        masked_rows = rows([v is not None for v in mask_mode_list])
        partial_rows = rows([
            mask_mode_list[i] is None
            and n_placeholders_list is not None and int(n_placeholders_list[i]) > 0
            for i in range(n_rows)
        ])
        splits.append(("expression/mask_all", 0, rows([v == "all" for v in mask_mode_list])))
        splits.append(("expression/mask_fittable", 0, rows([v == "fittable" for v in mask_mode_list])))
        # unmasked excludes partial rows: the four expression circumstances partition
        # (audit 2026-08-24 -- partial rows counted in both unmasked and partial).
        splits.append(("expression/unmasked", 0, ~masked_rows & ~partial_rows))
        if predict_y is not None:
            # Context is only the expression for the CONDITIONAL variant (the block
            # follows it); and a partial context withholds constants exactly as a
            # flagged one does (audit 2026-08-24 -- partial rows contaminated
            # unmasked_ctx). Unconditional rows live in predict_y/unconditional.
            conditional_rows = rows([draw is not None and bool(draw["conditional"])
                                     for draw in predict_y])
            ctx_masked = masked_rows | partial_rows
            splits.append(("predict_y/masked_ctx", 2, ctx_masked & conditional_rows))
            splits.append(("predict_y/unmasked_ctx", 2, ~ctx_masked & conditional_rows))
        if predict_residual is not None:
            residual_conditional = rows([draw is not None and bool(draw["conditional"])
                                         for draw in predict_residual])
            ctx_masked = masked_rows | partial_rows
            splits.append(("predict_residual/masked_ctx", 4, ctx_masked & residual_conditional))
            splits.append(("predict_residual/unmasked_ctx", 4, ~ctx_masked & residual_conditional))
        if n_placeholders_list is not None:
            splits.append(("expression/partial", 0, partial_rows))
            # The infilling block, split by how the placeholders arose: a flagged
            # (policy-determined) context vs an unflagged partial (random) one.
            splits.append(("constants/after_flagged", 3, masked_rows))
            splits.append(("constants/partial", 3, partial_rows))

    if predict_y is not None:
        conditional = rows([draw is not None and bool(draw["conditional"]) for draw in predict_y])
        unconditional = rows([draw is not None and not draw["conditional"] for draw in predict_y])
        splits.append(("predict_y/conditional", 2, conditional))
        splits.append(("predict_y/unconditional", 2, unconditional))

    if predict_residual is not None:
        # Prefix and suffix residual are different tasks: the unconditional variant
        # predicts the displacement with no expression in scope.
        conditional = rows([draw is not None and bool(draw["conditional"])
                            for draw in predict_residual])
        unconditional = rows([draw is not None and not draw["conditional"]
                              for draw in predict_residual])
        splits.append(("predict_residual/conditional", 4, conditional))
        splits.append(("predict_residual/unconditional", 4, unconditional))

    out: "dict[str, tuple[float, int]]" = {}
    for suffix, segment_id, row_mask in splits:
        member = valid & (seg == segment_id) & row_mask[:, None]
        if member.any():
            out[suffix] = (float(ce[member].sum()), int(member.sum()))
    return out


def _binary_auroc(scores: torch.Tensor, labels: torch.Tensor) -> float:
    """Rank-based AUROC (Mann-Whitney U). Ties in float logits are vanishingly rare, so
    average-rank tie correction is deliberately omitted."""
    order = scores.argsort()
    ranks = torch.empty(len(scores), dtype=torch.float64)
    ranks[order] = torch.arange(1, len(scores) + 1, dtype=torch.float64)
    n_pos = int(labels.sum())
    n_neg = len(labels) - n_pos
    return float((ranks[labels].sum() - n_pos * (n_pos + 1) / 2) / (n_pos * n_neg))


def _binary_auprc(scores: torch.Tensor, labels: torch.Tensor) -> float:
    """Average precision (the step-function AUPRC, sklearn's definition). At the
    outlier head's ~0.5% base rate this is the deployment metric AUROC cannot be:
    a 0.93-AUROC ranking can carry 4% precision at half recall (measured, the MAD-z
    baseline on the T16 val prior), and only AUPRC exposes that."""
    order = torch.argsort(scores, descending=True)
    hits = labels[order].to(torch.float64)
    tp = torch.cumsum(hits, dim=0)
    precision = tp / torch.arange(1, len(hits) + 1, dtype=torch.float64)
    return float((precision * hits).sum() / hits.sum())


class Trainer:
    """Manage end-to-end training for a ``FlashANSRModel``.

    Notes
    -----
    Parameters mirror the components required to run training while being
    flexible enough to support configuration driven instantiation via
    :meth:`Trainer.from_config`.
    """

    def __init__(
            self,
            model: FlashANSRModel,
            optimizer: torch.optim.Optimizer,
            amp_dtype: torch.dtype,
            scaler: torch.amp.GradScaler,
            lr_scheduler: LRScheduler | None,
            batch_size: int,
            train_dataset: FlashANSRDataset,
            val_dataset: FlashANSRDataset,
            gradient_accumulation_steps: int = 1,
            num_workers: int | None = None,
            validate_num_workers: int | None = None,
            config: dict[str, Any] = None) -> None:
        """Create a fully configured trainer instance.

        Parameters
        ----------
        model : FlashANSRModel
            The model to optimise.
        optimizer : torch.optim.Optimizer
            Optimiser responsible for updating model parameters.
        amp_dtype : torch.dtype
            Mixed precision dtype used with autocast.
        scaler : torch.amp.GradScaler
            Gradient scaler used for automatic mixed precision.
        lr_scheduler : LRScheduler or None
            Optional learning rate scheduler.
        batch_size : int
            Number of samples processed per training step.
        train_dataset : FlashANSRDataset
            Dataset providing training batches.
        val_dataset : FlashANSRDataset
            Dataset providing validation batches.
        gradient_accumulation_steps : int, default=1
            Number of micro-batches per optimizer step.
        num_workers : int or None, optional
            Number of worker processes for data generation.
        validate_num_workers : int or None, optional
            Worker count for the validation pool. The validation pool is kept
            alive next to the training pool, so both coexist in memory; a
            smaller validation pool trades validation wall time for the RAM
            the training pool can then spend. ``None`` = ``num_workers``.
        config : dict[str, Any] or None, optional
            Trainer configuration metadata (used for logging).
        """

        self.model = model
        self.optimizer = optimizer
        self.amp_dtype = amp_dtype
        self.scaler = scaler
        self.lr_scheduler = lr_scheduler
        self.batch_size = batch_size
        self.train_dataset = train_dataset
        self.val_dataset = val_dataset
        self.gradient_accumulation_steps = gradient_accumulation_steps
        self.config = config or {}
        self.num_workers = num_workers
        self.validate_num_workers = validate_num_workers
        self.device = torch.device("cpu")  # Updated during ``run``
        default_worker_preprocess = self.train_dataset.preprocessor is not None
        if isinstance(self.config, dict) and 'worker_preprocess' in self.config:
            self.worker_preprocess = bool(self.config.get('worker_preprocess'))
        else:
            self.worker_preprocess = default_worker_preprocess

        # Metrics and Loss Functions
        self.metrics_ignore_index = self.model.tokenizer["<pad>"]
        self.cross_entropy_loss = nn.CrossEntropyLoss(ignore_index=self.metrics_ignore_index)

        # Outlier-head auxiliary loss (noise mixture). weight 0.0 <=> off. pos_weight
        # rebalances the BCE positive class; the ruling starts at 1.0 (calibrated suspicion
        # scores) -- raise only if the head under-fires.
        self.outlier_loss_weight = float(self.config.get('outlier_loss_weight', 0.0))
        self.outlier_pos_weight = float(self.config.get('outlier_pos_weight', 1.0))
        # AUROC/AUPRC are rank statistics: they need every micro-batch's scores on the
        # host, which costs a device sync per micro-step on top of two sorts. Logged on
        # an interval; the loss itself is unaffected and logged every step.
        self.outlier_metrics_interval = int(self.config.get('outlier_metrics_interval', 50))
        # z-loss (log^2 Z) weight. 0.0 <=> off (the pre-2026-09-01 loss, bit-identical).
        # The v25 resume arms run 1e-4 (PaLM's coefficient); v26 replaces it with
        # head_pre_logits_norm in the model (owner ruling 2026-09-01).
        self.z_loss_weight = float(self.config.get('z_loss_weight', 0.0))
        if self.outlier_metrics_interval < 1:
            raise ValueError(
                f"outlier_metrics_interval must be at least 1, got {self.outlier_metrics_interval}")
        if self.outlier_loss_weight > 0.0 and self.model.outlier_head is None:
            raise ValueError(
                "outlier_loss_weight > 0 but the model has no outlier head "
                "(set outlier_head: true in the model config)")

        self.total_pflops = 0.0
        self.encoder_parameters = sum(p.numel() for p in self.model.encoder.parameters() if p.requires_grad)
        self.decoder_parameters = sum(p.numel() for p in self.model.decoder.parameters() if p.requires_grad)
        tokenizer_mapping = getattr(self.model.tokenizer, "token2idx", {})
        if not isinstance(tokenizer_mapping, dict):
            tokenizer_mapping = {}
        self._prompt_token_ids: dict[str, int | None] = {
            "complexity": tokenizer_mapping.get("<complexity>"),
        }
        self.decoder_max_seq_len = self._resolve_decoder_max_seq_len()

    @classmethod
    def from_config(cls, config: dict[str, Any] | str) -> "Trainer":
        """Instantiate a trainer from a config dictionary or YAML file path.

        Parameters
        ----------
        config : dict[str, Any] or str
            Dictionary of trainer settings or path to a YAML configuration file.

        Returns
        -------
        Trainer
            Trainer populated using the provided configuration.
        """
        config_ = load_config(config)

        if "trainer" in config_.keys():
            config_ = config_["trainer"]

        # Handle relative model paths
        if (
            isinstance(config, str)
            and isinstance(config_["model"], str)
            and config_["model"].startswith('.')
            and not os.path.isabs(config_["model"])
            and not os.path.normpath(config_["model"]).startswith(os.path.normpath(os.path.dirname(config)))
        ):
            # Only rewrite relative model paths that have not already been expanded
            config_["model"] = os.path.join(os.path.dirname(config), config_["model"])

        print(f'Creating model from {config_["model"]}')
        model = FlashANSRModel.from_config(config_["model"])

        print(f"Loading optimizer with config {config_['optimizer']}")
        optimizer = get_optimizer(
            config_['optimizer']['name'],
            params=model.parameters(),
            **config_['optimizer'].get('kwargs', {}),
        )

        # On CPU we avoid float16 autocast to prevent overflow; prefer bf16 when available.
        cpu_bf16_supported = bool(getattr(torch.cpu, "is_bf16_supported", lambda: False)())
        # Opt-in override (default behavior unchanged when unset). On pre-Ampere GPUs (e.g. Turing 2080 Ti)
        # torch.cuda.is_bf16_supported() returns True via emulation, which has no fp16 tensor cores and is
        # slow; FLASH_ANSR_AMP_DTYPE=fp16 forces native fp16 on such cards.
        _amp_override = os.environ.get("FLASH_ANSR_AMP_DTYPE", "").strip().lower()
        if _amp_override in ("fp16", "float16"):
            amp_dtype = torch.float16
        elif _amp_override in ("bf16", "bfloat16"):
            amp_dtype = torch.bfloat16
        elif _amp_override in ("fp32", "float32"):
            amp_dtype = torch.float32
        elif torch.cuda.is_available():
            amp_dtype = torch.bfloat16 if torch.cuda.is_bf16_supported() else torch.float16
        else:
            amp_dtype = torch.bfloat16 if cpu_bf16_supported else torch.float32

        scaler = torch.amp.GradScaler(enabled=amp_dtype == torch.float16)
        print(f'Using amp_dtype={amp_dtype}, GradScaler enabled={scaler.is_enabled()}')

        print(f'Loading lr_scheduler with config {config_["lr_schedule"]}')
        lr_scheduler = torch.optim.lr_scheduler.LambdaLR(
            optimizer=optimizer,
            lr_lambda=lambda step: pw_linear_schedule(step, config_['lr_schedule'])  # Pass the step and the points that define the piecewise linear schedule
        )

        num_workers = config_.get("num_workers", None)
        print(f'Using num_workers={num_workers} for data generation (set by config, may be overridden by run() arguments)')
        validate_num_workers = config_.get("validate_num_workers", None)
        print(f'Using validate_num_workers={validate_num_workers} for the validation pool (None = num_workers)')
        print(f'Loading train_dataset with config {config_["train_dataset"]}')
        train_dataset = FlashANSRDataset.from_config(config_["train_dataset"])

        print(f'Loading val_dataset with config {config_["val_dataset"]}')
        if isinstance(config_["val_dataset"], str):
            resolved_config_path = substitute_root_path(config_["val_dataset"])
            if os.path.isfile(resolved_config_path):
                val_dataset = FlashANSRDataset.from_config(resolved_config_path)
            elif os.path.isdir(resolved_config_path):
                _, val_dataset = FlashANSRDataset.load(directory=resolved_config_path)
            else:
                raise ValueError(f"val_dataset must be a file or directory, not {resolved_config_path}")
        elif isinstance(config_["val_dataset"], dict):
            val_dataset = FlashANSRDataset.from_config(config_["val_dataset"])
        else:
            raise ValueError(f"val_dataset must be a dict or path to a file or directory, not {config_['val_dataset']}")

        config_.setdefault('preprocess', False)

        return cls(
            model=model,
            optimizer=optimizer,
            amp_dtype=amp_dtype,
            scaler=scaler,
            lr_scheduler=lr_scheduler,
            batch_size=config_['batch_size'],
            train_dataset=train_dataset,
            val_dataset=val_dataset,
            gradient_accumulation_steps=config_.get("gradient_accumulation_steps", 1),
            num_workers=num_workers,
            validate_num_workers=validate_num_workers,
            config=config_,
        )

    def _setup_training_state(self, device: str, verbose: bool) -> None:
        """Move the model to ``device`` and reset training state.

        Parameters
        ----------
        device : str
            Torch device string used for training (for example ``"cuda"``).
        verbose : bool
            If ``True`` emit human readable status messages.
        """
        self.device = torch.device(device)
        self.model.to(self.device)

        self.total_pflops = 0.0

        if verbose:
            config_value = os.environ.get('PYTORCH_CUDA_ALLOC_CONF')
            if config_value:
                print(f"PYTORCH_CUDA_ALLOC_CONF is set to: '{config_value}'")
            else:
                print("PYTORCH_CUDA_ALLOC_CONF is not set.")

    def _resolve_decoder_max_seq_len(self) -> int:
        max_seq_len = getattr(self.model, 'decoder_max_seq_len', None)
        if max_seq_len is None:
            decoder = getattr(self.model, 'decoder', None)
            rope = getattr(decoder, 'rope', None) if decoder is not None else None
            max_seq_len = getattr(rope, 'max_seq_len', None) if rope is not None else None

        if max_seq_len is None:
            raise ValueError("Unable to determine decoder max sequence length from model.")

        if hasattr(max_seq_len, 'item'):
            max_seq_len = max_seq_len.item()

        return int(max_seq_len)

    def run_training(
            self,
            steps: int,
            preprocess: bool = False,
            device: str = "cpu",
            compile_mode: str | None = None,
            checkpoint_interval: int | None = None,
            checkpoint_directory: str | None = None,
            validate_interval: int | None = None,
            validate_size: int | None = None,
            validate_batch_size: int = 128,
            preprocess_in_worker: bool | None = None,
            resume_from: str | None = None,
            resume_step: int | None = None,
            verbose: bool = False) -> FlashANSRModel:
        """Execute the core training loop.

        Parameters
        ----------
        steps : int
            Number of optimisation steps to perform.
        preprocess : bool, default=False
            Whether to run dataset preprocessing before each batch.
        device : str, default='cpu'
            Target device identifier passed to :func:`torch.device`.
        compile_mode : str or None, optional
            Torch.compile mode for model compilation.
        checkpoint_interval : int or None, optional
            Save checkpoints every ``n`` steps when provided.
        checkpoint_directory : str or None, optional
            Directory for persisted checkpoints.
        validate_interval : int or None, optional
            Frequency (in steps) to run validation.
        validate_size : int or None, optional
            Limit the number of validation examples processed.
        validate_batch_size : int, default=128
            Batch size used for validation passes.
        preprocess_in_worker : bool or None, optional
            When ``True`` run dataset preprocessing inside producer workers
            instead of the main process. Defaults to the trainer configuration
            when ``None`` (which enables worker preprocessing whenever the
            dataset has a preprocessor).
        resume_from : str or None, optional
            Path to a checkpoint directory from which to resume.
        resume_step : int or None, optional
            Explicitly set the global step to resume from. Overrides any step
            inferred from the checkpoint.
        verbose : bool, default=False
            If ``True`` display progress bars and additional logs.

        Returns
        -------
        FlashANSRModel
            The trained model instance.
        """

        worker_preprocess = self.worker_preprocess if preprocess_in_worker is None else bool(preprocess_in_worker)
        if not preprocess:
            worker_preprocess = False

        try:
            self._setup_training_state(device, verbose=verbose)

            step_offset = 0
            if resume_from is not None:
                step_offset = self._load_checkpoint(resume_from, device=device)

            if compile_mode is not None:
                self.model = torch.compile(self.model, mode=compile_mode)

            if resume_step is not None:
                step_offset = int(resume_step)

            if step_offset < 0:
                raise ValueError("resume_step must be non-negative")

            remaining_steps = max(0, steps - step_offset)
            if verbose and step_offset > 0:
                print(f"Resuming from step {step_offset} with {remaining_steps} steps remaining (target={steps})")

            if remaining_steps == 0:
                return self.model

            pbar = tqdm(range(remaining_steps), disable=not verbose, smoothing=0, desc="Training")
            for local_step, batch in enumerate(
                    self.train_dataset.iterate(
                        steps=remaining_steps,
                        batch_size=self.batch_size,
                        preprocess=preprocess,
                        preprocess_in_worker=worker_preprocess,
                        num_workers=self.num_workers,
                        max_seq_len=self.decoder_max_seq_len)):
                global_step = step_offset + local_step
                self._train_step(batch, global_step, preprocess, do_optimizer_step=True)

                pbar.update(1)

                human_step = global_step + 1
                if validate_interval is not None and ((human_step % validate_interval == 0) or (human_step == steps)):
                    self._validate_step(human_step, validate_size, validate_batch_size, preprocess, worker_preprocess, verbose)

                if checkpoint_interval is not None and checkpoint_directory is not None and (human_step % checkpoint_interval == 0):
                    self._save_checkpoint(human_step, checkpoint_directory)

            pbar.close()
            self._release_datasets()
            return self.model

        except Exception:
            # Before re-raising: an AttributeError in here would replace the real one.
            self._release_datasets()
            raise

    def _release_datasets(self) -> None:
        """Release both datasets' worker pools. `val_dataset` is optional."""
        self.train_dataset.shutdown()
        if self.val_dataset is not None:
            self.val_dataset.shutdown()

    def run(
            self,
            project_name: str,
            entity: str,
            name: str,
            steps: int,
            preprocess: bool = False,
            device: str = "cpu",
            compile_mode: str | None = None,
            checkpoint_interval: int | None = None,
            checkpoint_directory: str | None = None,
            validate_interval: int | None = None,
            validate_size: int | None = None,
            validate_batch_size: int = 128,
            wandb_mode: Literal['online', 'offline', 'disabled'] = 'disabled',
            wandb_watch_log: Literal['gradients', 'parameters', 'all'] | None = None,
            wandb_watch_log_freq: int = 1000,
            preprocess_in_worker: bool | None = None,
            num_workers: int | None = None,
            validate_num_workers: int | None = None,
            resume_from: str | None = None,
            resume_step: int | None = None,
            verbose: bool = False) -> FlashANSRModel:
        """Train the model while managing the experiment lifecycle via W&B.

        Parameters
        ----------
        project_name : str
            Name of the Weights & Biases project.
        entity : str
            W&B entity (team or user) under which to log the run.
        name : str
            Run name displayed in W&B.
        steps : int
            Number of training iterations to execute.
        preprocess : bool, default=False
            Whether to preprocess dataset batches.
        device : str, default='cpu'
            Torch device string (for example ``"cpu"`` or ``"cuda"``).
        compile_mode : str or None, optional
            Torch.compile mode, if supported.
        checkpoint_interval : int or None, optional
            Step interval for checkpointing.
        checkpoint_directory : str or None, optional
            Directory where checkpoints are written when enabled.
        validate_interval : int or None, optional
            Step cadence for validation.
        validate_size : int or None, optional
            Maximum number of validation samples, if limited.
        validate_batch_size : int, default=128
            Batch size to use during validation.
        wandb_mode : {'online', 'offline', 'disabled'}, default='disabled'
            W&B initialisation mode. Defaults to ``'disabled'`` so a fresh install trains without
            requiring a W&B account or network; pass ``'online'`` to enable logging.
        wandb_watch_log : {'gradients', 'parameters', 'all'} or None, optional
            W&B ``watch`` setting controlling what to log.
        wandb_watch_log_freq : int, default=1000
            Frequency (steps) for W&B gradient/parameter logging.
        preprocess_in_worker : bool or None, optional
            When ``True`` run preprocessing inside dataset workers. Defaults to
            the trainer configuration when omitted (which enables worker
            preprocessing when available).
        num_workers : int or None, optional
            Number of worker processes for data generation.
        validate_num_workers : int or None, optional
            Override the validation-pool worker count (see the constructor).
        resume_from : str or None, optional
            Path to a checkpoint directory from which to resume training.
        resume_step : int or None, optional
            Override the inferred global step when resuming from ``resume_from``.
        verbose : bool, default=False
            When ``True`` print progress information to stdout.

        Returns
        -------
        FlashANSRModel
            The trained model instance.
        """

        if verbose:
            print(f"Training model ({self.model.n_params:,} parameters) for {steps:,} steps on device {device}")

        if num_workers is not None:
            print(f'Overriding trainer num_workers to {num_workers}')
            self.num_workers = num_workers

        if validate_num_workers is not None:
            print(f'Overriding trainer validate_num_workers to {validate_num_workers}')
            self.validate_num_workers = validate_num_workers

        wandb_config = unfold_config(copy.deepcopy(self.config))
        wandb_config.update({"steps": steps, "device": device, "verbose": verbose, "num_workers": num_workers,
                             "validate_num_workers": self.validate_num_workers})

        with wandb.init(config=wandb_config, project=project_name, entity=entity, name=name, mode=wandb_mode):  # type: ignore
            if wandb_mode != 'disabled':
                wandb.watch(self.model, log=wandb_watch_log, log_freq=wandb_watch_log_freq)  # type: ignore
                if verbose and wandb_watch_log is not None:
                    print(f'Watching model with wandb log={wandb_watch_log} at frequency {wandb_watch_log_freq}')

            return self.run_training(
                steps=steps,
                preprocess=preprocess,
                device=device,
                compile_mode=compile_mode,
                checkpoint_interval=checkpoint_interval,
                checkpoint_directory=checkpoint_directory,
                validate_interval=validate_interval,
                validate_size=validate_size,
                validate_batch_size=validate_batch_size,
                preprocess_in_worker=preprocess_in_worker,
                resume_from=resume_from,
                resume_step=resume_step,
                verbose=verbose
            )

    def _update_total_pflops(self, encoder_tokens: int, decoder_tokens: int, batch_size: int) -> None:
        """Accumulate an estimate of total pico floating-point operations.

        Parameters
        ----------
        encoder_tokens : int
            Number of encoder tokens processed in the current step.
        decoder_tokens : int
            Number of decoder tokens processed in the current step.
        batch_size : int
            Size of the current batch (prior to micro batching).
        """
        self.total_pflops += 6 * (self.encoder_parameters * encoder_tokens + self.decoder_parameters * decoder_tokens) * batch_size * 1e-15

    def _apply_prompt_mask(self, batch: dict[str, torch.Tensor]) -> None:
        """Mask loss contributions for prompt tokens when available."""
        prompt_mask = batch.get('prompt_mask')
        if prompt_mask is None:
            return

        if not isinstance(prompt_mask, torch.Tensor):
            prompt_mask = torch.as_tensor(prompt_mask, device=self.device, dtype=torch.bool)
            batch['prompt_mask'] = prompt_mask
        else:
            if prompt_mask.dtype != torch.bool:
                prompt_mask = prompt_mask.to(dtype=torch.bool)
            batch['prompt_mask'] = prompt_mask.to(device=self.device)

        labels = batch.get('labels')
        if labels is None or not isinstance(labels, torch.Tensor):
            return

        if labels.device != self.device:
            labels = labels.to(self.device)
            batch['labels'] = labels

        target_mask = batch['prompt_mask'][..., 1:]
        if target_mask.shape[-1] > labels.shape[-1]:
            target_mask = target_mask[..., :labels.shape[-1]]
        elif target_mask.shape[-1] < labels.shape[-1]:
            labels = labels[..., :target_mask.shape[-1]]
            batch['labels'] = labels

        labels[target_mask] = self.metrics_ignore_index

    def _apply_task_mask(self, batch: dict[str, torch.Tensor]) -> None:
        """Mask loss for v24 task-block structural tokens (openers, selectors, <float>
        values): same polarity (True = masked) and shifted-label discipline as the
        prompt mask. Supervision stays on content bytes and closing tags only."""
        task_mask = batch.get('task_mask')
        if task_mask is None:
            return

        if not isinstance(task_mask, torch.Tensor):
            task_mask = torch.as_tensor(task_mask, device=self.device, dtype=torch.bool)
            batch['task_mask'] = task_mask
        else:
            if task_mask.dtype != torch.bool:
                task_mask = task_mask.to(dtype=torch.bool)
            batch['task_mask'] = task_mask.to(device=self.device)

        labels = batch.get('labels')
        if labels is None or not isinstance(labels, torch.Tensor):
            return

        if labels.device != self.device:
            labels = labels.to(self.device)
            batch['labels'] = labels

        target_mask = batch['task_mask'][..., 1:]
        if target_mask.shape[-1] > labels.shape[-1]:
            target_mask = target_mask[..., :labels.shape[-1]]
        elif target_mask.shape[-1] < labels.shape[-1]:
            labels = labels[..., :target_mask.shape[-1]]
            batch['labels'] = labels

        labels[target_mask] = self.metrics_ignore_index

    def _apply_float_target_mask(self, batch: dict[str, torch.Tensor]) -> None:
        """Mask the loss terms whose TARGET token is ``<float>``, wherever they occur.

        In prompt spans ``<float>`` is already covered by the prompt mask; under the v24
        ``ieee754_mixed`` constants representation it also appears as the compact-constant
        form inside expression spans and must never become a training target (the model
        emits bits; the pipeline compacts them into ``<float>``). Same shifted-label
        discipline as :meth:`_apply_prompt_mask`; a no-op when the vocabulary has no
        ``<float>`` token.
        """
        tokenizer_mapping = getattr(self.model.tokenizer, 'token2idx', None)
        if not isinstance(tokenizer_mapping, dict):
            return
        float_token_id = tokenizer_mapping.get('<float>')
        if float_token_id is None:
            return

        labels = batch.get('labels')
        input_ids = batch.get('input_ids')
        if not isinstance(labels, torch.Tensor) or not isinstance(input_ids, torch.Tensor):
            return

        mask_float_targets(labels, input_ids, float_token_id, int(self.metrics_ignore_index))

    def _outlier_scores(self, batch: dict[str, Any]) -> tuple[torch.Tensor, torch.Tensor] | None:
        """Per-point outlier-head logits and contamination labels over valid support points.

        ``None`` when inactive (no head, or the batch carries no mixture labels). Reads the
        per-point representations captured by the SAME model forward that produced the
        next-token logits -- never a second encoder pass.
        """
        head = self.model.outlier_head
        if head is None or 'outlier_mask' not in batch:
            return None
        point_representations = self.model.point_representations
        if point_representations is None:
            return None
        logits = head(point_representations).squeeze(-1)
        valid = batch['data_attn_mask'].to(logits.device)
        labels = batch['outlier_mask'].to(logits.device)
        return logits[valid], labels[valid]

    def _outlier_loss(self, scored: tuple[torch.Tensor, torch.Tensor]) -> torch.Tensor:
        logits, labels = scored
        if logits.numel() == 0:
            return torch.zeros((), device=logits.device)
        pos_weight = torch.tensor(self.outlier_pos_weight, device=logits.device, dtype=logits.dtype)
        return nn.functional.binary_cross_entropy_with_logits(
            logits, labels.to(logits.dtype), pos_weight=pos_weight)

    def _train_step(self, batch: dict[str, torch.Tensor], step: int, preprocess: bool, do_optimizer_step: bool = True) -> None:
        """Perform a single optimisation step with optional gradient accumulation.

        Parameters
        ----------
        batch : dict[str, torch.Tensor]
            Batched tensors produced by the training dataset.
        step : int
            Zero-indexed global training step.
        preprocess : bool
            Whether to preprocess batch data prior to collation.
        do_optimizer_step : bool, default=True
            When ``False`` skip the optimiser update (useful for gradient
            accumulation across micro-batches).
        """
        self.model.train()

        total_ce_loss = 0.0
        total_outlier_loss = 0.0
        total_z_loss = 0.0
        total_loss = 0.0
        task_ce_sums: dict[str, list[float]] = {}
        split_ce_sums: dict[str, list[float]] = {}
        train_outlier_scores: list[torch.Tensor] = []
        train_outlier_labels: list[torch.Tensor] = []
        # Both halves of the ranking metrics share one cadence, so a step that logs them
        # always has the complete set of scores behind it.
        rank_metrics_step = (self.outlier_loss_weight > 0.0
                             and step % self.outlier_metrics_interval == 0)

        # Split the batch into micro-batches to support gradient accumulation
        if len(batch['x_tensors']) % self.gradient_accumulation_steps != 0:
            raise ValueError(
                f"Batch of size {len(batch['x_tensors'])} is not divisible by "
                f"gradient_accumulation_steps {self.gradient_accumulation_steps}; the integer split "
                f"below would silently drop the remainder samples. Use a batch size that is a "
                f"multiple of gradient_accumulation_steps (for pre-compiled datasets this can also "
                f"be a ragged FINAL batch - re-compile with a compatible batch size)."
            )
        for acc_step in range(self.gradient_accumulation_steps):
            micro_batch_size = len(batch['x_tensors']) // self.gradient_accumulation_steps
            micro_batch = {k: v[acc_step * micro_batch_size:(acc_step + 1) * micro_batch_size] for k, v in batch.items()}
            micro_batch = self.train_dataset.collate(micro_batch, device=self.device)
            self._apply_prompt_mask(micro_batch)
            self._apply_task_mask(micro_batch)
            self._apply_float_target_mask(micro_batch)

            data_tensor = torch.cat([micro_batch['x_tensors'], micro_batch['y_tensors']], dim=-1)

            if self.amp_dtype == torch.float32:
                autocast_context = torch.autocast(self.device.type, dtype=self.amp_dtype, enabled=False)
            else:
                autocast_context = torch.autocast(self.device.type, dtype=self.amp_dtype)

            with autocast_context:
                logits = self.model(micro_batch['input_ids'], data_tensor, input_num=micro_batch.get('input_num', None), data_attn_mask=micro_batch['data_attn_mask'].to(self.device), condition_mask=micro_batch.get('condition_mask', None))
                flat_logits = logits[:, :-1].reshape(-1, logits.shape[-1])
                flat_labels = micro_batch['labels'].reshape(-1)
                valid_labels = flat_labels != self.metrics_ignore_index
                if not valid_labels.any():
                    ce_loss = torch.zeros((), device=self.device, dtype=logits.dtype)
                else:
                    ce_loss = self.cross_entropy_loss(flat_logits, flat_labels)

                # Force every parameter to contribute to the loss so that gradient
                # tracking tools (e.g. wandb.watch) do not encounter ``None`` gradients
                # for frozen or unused tensors.
                param_sum = sum(p.sum() for p in self.model.parameters())
                zero_loss = 0.0 * param_sum

                outlier_loss = torch.zeros((), device=self.device, dtype=ce_loss.dtype)
                if self.outlier_loss_weight > 0.0:
                    scored = self._outlier_scores(micro_batch)
                    if scored is not None:
                        outlier_loss = self._outlier_loss(scored)
                        if rank_metrics_step:
                            train_outlier_scores.append(scored[0].detach().float().cpu())
                            train_outlier_labels.append(scored[1].detach().cpu())

                z_loss = torch.zeros((), device=self.device, dtype=ce_loss.dtype)
                if self.z_loss_weight > 0.0 and valid_labels.any():
                    z_loss = _z_loss(flat_logits, valid_labels)

                loss = (ce_loss
                        + self.outlier_loss_weight * outlier_loss
                        + self.z_loss_weight * z_loss) / self.gradient_accumulation_steps + zero_loss

            # If the loss is nan or inf, stop the training
            if not torch.isfinite(loss):
                raise ValueError(f"Loss is {loss.item()}, stopping training")

            self.scaler.scale(loss).backward()
            total_ce_loss += ce_loss.item()
            total_outlier_loss += outlier_loss.item()
            total_z_loss += z_loss.item()
            with torch.no_grad():
                if 'task_segments' in micro_batch:
                    for name, (ce_sum, count) in _per_task_ce(
                            logits.detach(), micro_batch['labels'],
                            micro_batch['task_segments'], self.metrics_ignore_index).items():
                        entry = task_ce_sums.setdefault(name, [0.0, 0])
                        entry[0] += ce_sum
                        entry[1] += count
                # Unconditional (audit 2026-08-24): the segments-None fallback treats
                # every position as expression so BASE arms log the anchor too --
                # gating it on task_segments made that fallback dead code.
                for name, (ce_sum, count) in _ce_split_metrics(
                        micro_batch, logits.detach(), self.metrics_ignore_index).items():
                    entry = split_ce_sums.setdefault(name, [0.0, 0])
                    entry[0] += ce_sum
                    entry[1] += count
            total_loss += loss.item() * self.gradient_accumulation_steps

        self._update_total_pflops(encoder_tokens=data_tensor.shape[1], decoder_tokens=micro_batch['input_ids'].shape[1], batch_size=len(batch['x_tensors']))

        # Unscale/clip/zero belong to the step, not the backward: with do_optimizer_step=False
        # the gradients must survive into the next call. zero_grad moves here (after the step)
        # from the top of the method for the same reason.
        if do_optimizer_step:
            self.scaler.unscale_(self.optimizer)
            total_gradient_norm = torch.nn.utils.clip_grad_norm_(self.model.parameters(), 2.0)
            self.scaler.step(self.optimizer)
            self.scaler.update()
            self.optimizer.zero_grad()

            # Log metrics and update scheduler after the optimizer step
            # Positional call when no extras: monkeypatched/legacy 4-arg loggers keep working.
            extra: dict[str, float] = {}
            if self.z_loss_weight > 0.0:
                extra["train_z_loss"] = total_z_loss
            if self.outlier_loss_weight > 0.0:
                extra["train_outlier_loss"] = total_outlier_loss
                if train_outlier_scores:
                    scores = torch.cat(train_outlier_scores)
                    outlier_labels = torch.cat(train_outlier_labels).bool()
                    if outlier_labels.any() and (~outlier_labels).any():
                        extra["train_outlier_auroc"] = _binary_auroc(scores, outlier_labels)
                        extra["train_outlier_auprc"] = _binary_auprc(scores, outlier_labels)
            for name, sums in task_ce_sums.items():
                extra[f"train_ce_{name}"] = sums[0] / sums[1]
            for name, sums in split_ce_sums.items():
                extra[f"ce_split/train/{name}"] = sums[0] / sums[1]
            for counter_key, value in getattr(self.train_dataset, "stream_counters", {}).items():
                extra[f"data/{counter_key}"] = value
            if extra:
                self._log_metrics(step, total_ce_loss, total_loss, total_gradient_norm, extra=extra)
            else:
                self._log_metrics(step, total_ce_loss, total_loss, total_gradient_norm)
            if self.lr_scheduler is not None:
                self.lr_scheduler.step()

    def _effective_validate_num_workers(self) -> int | None:
        """Worker count for the validation pool: the explicit override, else ``num_workers``."""
        return self.num_workers if self.validate_num_workers is None else self.validate_num_workers

    def _validate_step(self, step: int, size: int | None, batch_size: int, preprocess: bool, worker_preprocess: bool, verbose: bool) -> None:
        """Evaluate the model on the validation split and log aggregate metrics.

        Parameters
        ----------
        step : int
            Global training step at which validation is triggered.
        size : int or None
            Optional limit on the number of validation examples.
        batch_size : int
            Number of samples per validation batch.
        preprocess : bool
            Whether to preprocess validation batches.
        worker_preprocess : bool
            Whether preprocessing should run inside dataset workers.
        verbose : bool
            If ``True`` display a validation progress bar.
        """
        self.model.eval()

        val_ce_loss = 0.0
        val_z_loss = 0.0
        total_items = 0
        val_outlier_scores: list[torch.Tensor] = []
        val_outlier_labels: list[torch.Tensor] = []
        val_task_ce_sums: dict[str, list[float]] = {}
        val_split_ce_sums: dict[str, list[float]] = {}

        with torch.no_grad():
            if size is None:
                steps = len(self.val_dataset) // batch_size
            else:
                steps = size // batch_size

            pbar = tqdm(total=steps, leave=False, position=1, disable=not verbose, desc="Validating", smoothing=0.0)
            for batch in self.val_dataset.iterate(
                    size=size,
                    batch_size=batch_size,
                    preprocess=preprocess,
                    preprocess_in_worker=worker_preprocess,
                    num_workers=self._effective_validate_num_workers(),
                    max_seq_len=self.decoder_max_seq_len,
                    # Validation runs many times over the same settings; each cold start
                    # would make every worker re-parse the holdout catalogs.
                    keep_alive=True):
                batch = self.val_dataset.collate(batch, device=self.device)
                self._apply_prompt_mask(batch)
                self._apply_task_mask(batch)
                self._apply_float_target_mask(batch)
                data_tensor = torch.cat([batch['x_tensors'], batch['y_tensors']], dim=-1)

                with torch.autocast(device_type=self.device.type, dtype=self.amp_dtype):
                    # val keeps unconditional_prob=0.0 -> condition_mask is all-True (== None == fully
                    # conditioned), so val CE stays a pure conditioned metric comparable across runs.
                    logits = self.model(batch['input_ids'], data_tensor, input_num=batch.get('input_num', None), data_attn_mask=batch['data_attn_mask'].to(self.device), condition_mask=batch.get('condition_mask', None))
                    flat_logits = logits[:, :-1].reshape(-1, logits.shape[-1])
                    flat_labels = batch['labels'].reshape(-1)
                    valid_labels = flat_labels != self.metrics_ignore_index
                    if not valid_labels.any():
                        ce_loss = torch.zeros((), device=self.device, dtype=logits.dtype)
                    else:
                        ce_loss = self.cross_entropy_loss(flat_logits, flat_labels)

                    if self.z_loss_weight > 0.0 and valid_labels.any():
                        val_z_loss += _z_loss(flat_logits, valid_labels).item() * flat_labels.shape[0]

                    # Accumulate metrics for each batch
                    val_ce_loss += ce_loss.item() * flat_labels.shape[0]
                    total_items += flat_labels.shape[0]

                    if self.outlier_loss_weight > 0.0:
                        scored = self._outlier_scores(batch)
                        if scored is not None:
                            val_outlier_scores.append(scored[0].detach().float().cpu())
                            val_outlier_labels.append(scored[1].detach().cpu())
                    if 'task_segments' in batch:
                        for name, (ce_sum, count) in _per_task_ce(
                                logits.detach(), batch['labels'],
                                batch['task_segments'], self.metrics_ignore_index).items():
                            entry = val_task_ce_sums.setdefault(name, [0.0, 0])
                            entry[0] += ce_sum
                            entry[1] += count
                    # Unconditional, mirroring the train side (audit 2026-08-24).
                    for name, (ce_sum, count) in _ce_split_metrics(
                            batch, logits.detach(), self.metrics_ignore_index).items():
                        entry = val_split_ce_sums.setdefault(name, [0.0, 0])
                        entry[0] += ce_sum
                        entry[1] += count

                pbar.update(1)
            pbar.close()

        # Calculate average metrics
        avg_val_ce_loss = val_ce_loss / total_items if total_items > 0 else 0.0

        outlier_metrics: dict[str, float] | None = None
        if val_task_ce_sums:
            outlier_metrics = {f"val_ce_{name}": ce_sum / count
                               for name, (ce_sum, count) in val_task_ce_sums.items()}
            outlier_metrics.update({f"ce_split/val/{name}": ce_sum / count
                                    for name, (ce_sum, count) in val_split_ce_sums.items()})
        if val_outlier_scores:
            scores = torch.cat(val_outlier_scores)
            labels = torch.cat(val_outlier_labels).bool()
            bce = nn.functional.binary_cross_entropy_with_logits(
                scores, labels.float(), pos_weight=torch.tensor(self.outlier_pos_weight))
            outlier_metrics = dict(outlier_metrics or {})
            outlier_metrics["val_outlier_loss"] = float(bce)
            if labels.any() and (~labels).any():
                outlier_metrics["val_outlier_auroc"] = _binary_auroc(scores, labels)
                outlier_metrics["val_outlier_auprc"] = _binary_auprc(scores, labels)

        # Composite val_loss mirrors train_loss (ce + weighted auxiliary terms).
        val_composite = avg_val_ce_loss
        if outlier_metrics is not None and "val_outlier_loss" in outlier_metrics:
            val_composite = avg_val_ce_loss + self.outlier_loss_weight * outlier_metrics["val_outlier_loss"]
        outlier_metrics = dict(outlier_metrics or {})
        if self.z_loss_weight > 0.0:
            avg_val_z_loss = val_z_loss / total_items if total_items > 0 else 0.0
            outlier_metrics["val_z_loss"] = avg_val_z_loss
            val_composite = val_composite + self.z_loss_weight * avg_val_z_loss
        outlier_metrics["val_loss"] = val_composite

        # Log averaged validation metrics (positional when the feature is off, see _log_metrics)
        if outlier_metrics is not None:
            self._log_validation_metrics(step, avg_val_ce_loss, extra=outlier_metrics)
        else:
            self._log_validation_metrics(step, avg_val_ce_loss)

    def _save_checkpoint(self, step: int, checkpoint_directory: str) -> None:
        """Persist model weights, optimiser state, and config for ``step``.

        Parameters
        ----------
        step : int
            Training step associated with the persisted checkpoint.
        checkpoint_directory : str
            Directory into which the checkpoint will be written.
        """
        save_directory = os.path.join(checkpoint_directory, f"checkpoint_{step}")
        self.model.save(directory=save_directory, errors='ignore')
        torch.save(self.optimizer.state_dict(), os.path.join(save_directory, "optimizer.pt"))
        if self.lr_scheduler is not None:
            torch.save(self.lr_scheduler.state_dict(), os.path.join(save_directory, "lr_scheduler.pt"))
        if self.scaler is not None:
            torch.save(self.scaler.state_dict(), os.path.join(save_directory, "scaler.pt"))
        torch.save({"step": step, "total_pflops": self.total_pflops}, os.path.join(save_directory, "training_state.pt"))
        save_config(
            load_config(self.config, resolve_paths=True),
            directory=save_directory,
            filename='train.yaml',
            reference='relative',
            recursive=True,
            resolve_paths=True)
        print(f"Checkpoint saved at {save_directory}")

    def _infer_resume_step(self, checkpoint_directory: str) -> int | None:
        """Infer the resume step from the checkpoint directory name."""
        base = os.path.basename(os.path.normpath(checkpoint_directory))
        prefix = "checkpoint_"
        if base.startswith(prefix):
            suffix = base[len(prefix):]
            if suffix.isdigit():
                return int(suffix)
        return None

    def _load_checkpoint(self, checkpoint_directory: str, device: str) -> int:
        """Load training state from ``checkpoint_directory`` and return the step."""

        checkpoint_directory = substitute_root_path(checkpoint_directory)
        if not os.path.isdir(checkpoint_directory):
            raise FileNotFoundError(f"Checkpoint directory not found: {checkpoint_directory}")

        optimizer_state_path = os.path.join(checkpoint_directory, "optimizer.pt")
        scheduler_state_path = os.path.join(checkpoint_directory, "lr_scheduler.pt")
        scaler_state_path = os.path.join(checkpoint_directory, "scaler.pt")
        training_state_path = os.path.join(checkpoint_directory, "training_state.pt")

        map_location = torch.device(device)

        # Weights are safetensors; the optimiser/scaler/scheduler state below is not all
        # tensors and stays on torch.save.
        load_weights(self.model, checkpoint_directory, device=map_location)
        self.optimizer.load_state_dict(torch.load(optimizer_state_path, map_location=map_location))

        resume_step: int | None = None
        if os.path.isfile(training_state_path):
            training_state = torch.load(training_state_path, map_location=map_location)
            if isinstance(training_state, dict):
                step_value = training_state.get("step")
                if step_value is not None:
                    try:
                        resume_step = int(step_value)
                    except (TypeError, ValueError):
                        resume_step = None

                self.total_pflops = float(training_state.get("total_pflops", self.total_pflops))

        if resume_step is None:
            resume_step = self._infer_resume_step(checkpoint_directory)

        if self.lr_scheduler is not None:
            if os.path.isfile(scheduler_state_path):
                self.lr_scheduler.load_state_dict(torch.load(scheduler_state_path, map_location=map_location))
            else:
                if resume_step is None:
                    print("Warning: lr_scheduler state missing and resume step unknown; set resume_step explicitly to align LR schedule.")
                else:
                    self.lr_scheduler.last_epoch = resume_step - 1
                    print(f"Warning: lr_scheduler state missing; reconstructing schedule at step {resume_step}.")

        if self.scaler is not None:
            if os.path.isfile(scaler_state_path):
                self.scaler.load_state_dict(torch.load(scaler_state_path, map_location=map_location))
            else:
                print("Warning: scaler state missing; starting with a fresh GradScaler.")

        if resume_step is None:
            raise ValueError(
                "Unable to infer resume step; provide resume_step explicitly or name the checkpoint directory checkpoint_<step>.")

        return resume_step

    def _log_metrics(self, step: int, ce_loss: float, total_loss: float, total_gradient_norm: torch.Tensor,
                     extra: "dict[str, float] | None" = None) -> None:
        """Submit training metrics for the current batch to Weights & Biases.

        Parameters
        ----------
        step : int
            Global training step the metrics correspond to.
        ce_loss : float
            Cross-entropy loss for the batch.
        total_loss : float
            Total loss (including auxiliary terms) for the batch.
        total_gradient_norm : torch.Tensor
            Gradient norm measured after clipping.
        """

        log_data = {
            "total_gradient_norm": total_gradient_norm.item(),
            "train_ce_loss": ce_loss,
            "train_loss": total_loss,
            "lr": self.optimizer.param_groups[0]['lr'],
            "total_pflops": self.total_pflops,
        }
        if extra:
            log_data.update(extra)

        wandb.log(log_data, step=step)  # type: ignore

    def _log_validation_metrics(self, step: int, val_ce_loss: float,
                                extra: "dict[str, float] | None" = None) -> None:
        """Submit aggregated validation metrics to Weights & Biases.

        Parameters
        ----------
        step : int
            Global training step the metrics correspond to.
        val_ce_loss : float
            Mean validation cross-entropy loss.
        """
        log_data = {
            "val_ce_loss": val_ce_loss,
        }
        if extra:
            log_data.update(extra)
        wandb.log(log_data, step=step)  # type: ignore
