"""Public inference result types for :meth:`FlashANSR.infer`.

A single inference over one problem yields an :class:`InferenceResult`: the score-sorted refined
:class:`Candidate`s (the ones that fitted), PLUS a :class:`CandidateLedger` -- the FULL generation
pool joined with the refined survivors and classified FIT_OK / FIT_FAILED / INVALID. The ledger is
the lean, columnar "all candidates" object a benchmark's save-all tier persists; it owns no model
objects (no refiner / no lambda), so it streams and serializes cheaply.

This replaces a consumer scraping ``model._results`` / ``predict(nth_best_beam=...)`` after ``fit``:
the candidate set + every field a benchmark stores is returned directly.
"""
from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any, Callable, Sequence

import numpy as np

from flash_ansr.refine import fit_sort_key
from flash_ansr.scoring import PARETO_RANK_NOT_COMPUTED

# Per-candidate fit outcome (a candidate generated by the model + put through constant refinement).
FIT_OK = 0        # refined successfully (finite fvu); carries fitted constants
FIT_FAILED = 1    # a VALID expression whose constant refinement did not converge
INVALID = 2       # not a valid expression (rejected before refinement)


@dataclass
class Candidate:
    """One refined survivor (a generated expression that fitted). Rich, for interactive use."""

    raw_beam: list[int]                 # full beam ids -- the dedup-unique candidate identity
    expression: list[str]               # decoded skeleton tokens (constants as placeholders)
    expression_prefix: list[str]        # constants substituted, x1..xN vars, raw PREFIX tokens (symbolic_data.token_ops.normalize_expression for canonical form)
    expression_infix: str               # human-readable prediction: constants substituted, vars MAPPED, INFIX str (== get_expression(map_variables=True))
    skeleton_prefix: list[str]          # normalized skeleton (constants as placeholders)
    constants: list[float]              # best-fit constant values (REFINED by the optimizer)
    constants_emitted: list[float] | None    # what the MODEL predicted, before refinement
    log_prob: float
    score: float                        # the scalar ranking score ('mdl' / 'weighted'); nan under 'pareto'
    fvu: float
    n_nodes: int                        # TOKEN COUNT of the emitted expression (the `n_nodes` ranking metric)
    mu: float | None                    # simplipy complexity of the masked SKELETON -- the unit fit(complexity=) consumes
    mdl: float | None                   # simplipy mu of the REALIZED expression (constants substituted), milli-bits -- the RANKING currency; None if unpriceable
    constant_count: int
    pruned_variant: bool                # synthesized during constant-pruning (not from generation)
    pareto_rank: int                    # front index under 'pareto' (0 = non-dominated); -1 when ranked by a scalar score
    rank: int                           # position in the score-sorted candidate list (0 = the returned answer)
    y_pred: np.ndarray | None = None        # on support X -- populated only for the top_k (opt-in; OOM otherwise)
    y_pred_val: np.ndarray | None = None    # on validation X -- top_k only
    spelling: str | None = None         # constant-ladder variant: which fitted constants were re-spelled how (``c0=/ 3 2;c2=0``); None for a fitted draw
    typed_frozen: int = 0               # PREDICTED literals kept verbatim in a typed position (pow exponent / rootn index); 0 on the shipped path
    typed_thaw: str | None = None       # a `freeze_then_free` duplicate: the typed token indices it re-fitted; None otherwise


@dataclass
class CandidateLedger:
    """The FULL generation pool U refined survivors, classified -- the lean columnar "all candidates"
    object. Holds NO model objects.

    The ranking columns (``n_nodes``, ``n_constants``, ``mdl``, ``score``, ``pareto_rank``, ``rank``)
    are copied from the refined result rows, never re-derived from the raw beam ids (which would
    need the tokenizer and the span mapper). Non-fitted rows carry nan / -1. ``rank`` is the
    position in the score-sorted candidate list, so an offline re-sort of the ledger can be checked
    against what the live run actually returned (rank 0)."""

    token_lists: list[list[int]]
    fvu: list[float]
    log_prob: list[float]
    valid: list[int]
    fit_status: list[int]               # FIT_OK / FIT_FAILED / INVALID
    constants: list[list[float]]
    n_nodes: list[int] = field(default_factory=list)          # -1 for non-fitted rows
    n_constants: list[int] = field(default_factory=list)      # -1 for non-fitted rows
    mdl: list[float] = field(default_factory=list)            # milli-bits; nan if unpriced / non-fitted
    score: list[float] = field(default_factory=list)          # nan for non-fitted rows and under 'pareto'
    pareto_rank: list[int] = field(default_factory=list)      # -1 unless ranked by 'pareto'
    rank: list[int] = field(default_factory=list)             # -1 for non-fitted rows
    result_index: list[int] = field(default_factory=list)     # index into InferenceResult.candidates; -1 if none
    spelling: list[str] = field(default_factory=list)        # constant-ladder record; '' for a fitted draw / non-fitted row
    parent: list[int] = field(default_factory=list)          # ledger row of the beam a ladder variant was re-spelled from; -1 otherwise

    def __len__(self) -> int:
        return len(self.token_lists)


@dataclass
class InferenceResult:
    """The result of one :meth:`FlashANSR.infer`: score-sorted refined candidates + the full ledger."""

    candidates: list[Candidate]         # FIT_OK survivors, score-sorted (best first)
    ledger: CandidateLedger             # full generation pool U refined, classified
    generation_time: float
    refinement_time: float
    variable_mapping: dict[str, str] = field(default_factory=dict)

    @property
    def best(self) -> Candidate | None:
        return self.candidates[0] if self.candidates else None

    def to_dataframe(self) -> "Any":
        import pandas as pd
        rows = [
            {
                "expression_infix": c.expression_infix,
                "expression_prefix": c.expression_prefix,
                "skeleton_prefix": c.skeleton_prefix,
                "constants": c.constants,
                "log_prob": c.log_prob,
                "score": c.score,
                "fvu": c.fvu,
                "n_nodes": c.n_nodes,
                "mu": c.mu,
                "mdl": c.mdl,
                "constant_count": c.constant_count,
                "pruned_variant": c.pruned_variant,
                "pareto_rank": c.pareto_rank,
                "rank": c.rank,
                "spelling": c.spelling,
            }
            for c in self.candidates
        ]
        return pd.DataFrame(rows)


def _best_constants(result: dict) -> list[float]:
    """Best-fit constants of a refined result (``fits[0][0]``), else empty."""
    fits = result.get("fits") or []
    if not fits:
        return []
    # fit_sort_key, not a bare loss key: `min` over a list containing NaN returns whatever
    # happens to be first (NaN loses every comparison), which would publish a DIVERGENT
    # restart's constants on Candidate.constants while a finite fit sat in the same list.
    best = min(fits, key=fit_sort_key)             # (constants, cov, loss) -> lowest FINITE loss
    arr = np.asarray(best[0], dtype=np.float64).ravel()
    return arr.tolist()


def build_candidate_ledger(
    raw_beams: Sequence[Sequence[int]],
    log_probs: Sequence[float],
    results: Sequence[dict],
    *,
    decode_expr: Callable[[list[int]], list[str] | None] | None = None,
    is_valid: Callable[[list[str]], bool] | None = None,
) -> CandidateLedger:
    """Join the FULL generation pool with the refined results into a classified columnar ledger.

    ``raw_beams`` / ``log_probs`` are the unique generation pool; ``results`` are the refined
    survivors (each dict carries ``raw_beam`` -- the dedup-unique identity -- plus ``fvu``,
    ``log_prob``, ``fits``). A gen candidate present in ``results`` is FIT_OK; one ABSENT is
    not-fitted and split FIT_FAILED vs INVALID by re-running validity ONLY on that (small) subset
    via ``decode_expr`` + ``is_valid`` (so the bulk pays no per-candidate cost). Pruned variants
    (present in ``results``, synthesized in refinement, absent from the gen pool) ride along FIT_OK.
    The token column is the raw beam ids (decode offline if needed).
    """
    def _key(raw_beam: Sequence[Any], spelling: Any, typed_thaw: Any = None) -> tuple:
        return (tuple(int(t) for t in raw_beam), str(spelling or ""), str(typed_thaw or ""))

    # Keyed on the beam AND what was done to it: a re-spelled variant (constant ladder) and a
    # typed-span duplicate (`refiner_typed_spans='freeze_then_free'`, which refits the candidate with
    # its predicted exponent thawed) both share their parent's beam and are rows of their own. Keying
    # on the beam alone made a duplicate collide with its parent, so the ledger came back SHORTER
    # than the candidate list it is supposed to cover.
    fitted: dict[tuple, tuple[int, dict]] = {
        _key(r["raw_beam"], r.get("spelling"), r.get("typed_thaw")): (i, r) for i, r in enumerate(results)}
    # a variant that REPLACED its parent (a tie in score) is the fitted result of that beam
    for i, r in enumerate(results):
        if r.get("spelling") and r.get("replaces_parent"):
            fitted.setdefault(_key(r["raw_beam"], "", r.get("typed_thaw")), (i, r))

    token_lists: list[list[int]] = []
    fvu: list[float] = []
    log_prob: list[float] = []
    valid: list[int] = []
    fit_status: list[int] = []
    constants: list[list[float]] = []
    n_nodes: list[int] = []
    n_constants: list[int] = []
    mdl: list[float] = []
    score: list[float] = []
    pareto_rank: list[int] = []
    rank: list[int] = []
    result_index: list[int] = []
    spelling: list[str] = []
    parent: list[int] = []
    seen: set[tuple] = set()

    def _fitted_row(i: int, r: dict) -> None:
        fvu.append(float(r["fvu"]))
        valid.append(1)
        fit_status.append(FIT_OK)
        constants.append(_best_constants(r))
        n_nodes.append(len(r.get("expression") or []))
        cc = r.get("constant_count")
        n_constants.append(-1 if cc is None else int(cc))
        m = r.get("mdl")
        mdl.append(float("nan") if m is None else float(m))
        sc = r.get("score")
        score.append(float("nan") if sc is None else float(sc))
        pareto_rank.append(int(r.get("pareto_rank", PARETO_RANK_NOT_COMPUTED)))
        rank.append(i)              # `results` arrive score-sorted: the list position IS the rank
        result_index.append(i)
        spelling.append(str(r.get("spelling") or ""))
        parent.append(-1)

    def _unfitted_row(v: bool) -> None:
        fvu.append(float("nan"))
        constants.append([])
        valid.append(1 if v else 0)
        fit_status.append(FIT_FAILED if v else INVALID)
        n_nodes.append(-1)
        n_constants.append(-1)
        mdl.append(float("nan"))
        score.append(float("nan"))
        pareto_rank.append(PARETO_RANK_NOT_COMPUTED)
        rank.append(-1)
        result_index.append(-1)
        spelling.append("")
        parent.append(-1)

    for rb, lp in zip(raw_beams, log_probs):
        rb_list = [int(t) for t in rb]
        key = _key(rb_list, "")
        seen.add(key)
        token_lists.append(rb_list)
        hit = fitted.get(key)
        if hit is not None:
            i, r = hit
            log_prob.append(float(r.get("log_prob", lp)))
            _fitted_row(i, r)
            continue
        v = True
        if decode_expr is not None and is_valid is not None:
            try:
                toks = decode_expr(rb_list)
                v = bool(is_valid(toks)) if toks is not None else False
            except Exception:  # noqa: BLE001
                v = False
        log_prob.append(float(lp))
        _unfitted_row(v)

    for i, pruned in enumerate(results):
        key = _key(pruned["raw_beam"], pruned.get("spelling"), pruned.get("typed_thaw"))
        if key in seen or (pruned.get("spelling") and pruned.get("replaces_parent")
                           and _key(pruned["raw_beam"], "", pruned.get("typed_thaw")) in seen):
            continue
        seen.add(key)
        token_lists.append(list(key[0]))
        log_prob.append(float(pruned.get("log_prob", float("nan"))))
        _fitted_row(i, pruned)

    # a ladder variant points at the row of the beam it was re-spelled from
    row_of: dict[tuple, int] = {}
    for row, (rb, sp) in enumerate(zip(token_lists, spelling)):
        if not sp:
            row_of.setdefault(tuple(rb), row)
    for row, (rb, sp) in enumerate(zip(token_lists, spelling)):
        if sp:
            parent[row] = row_of.get(tuple(rb), -1)
    return CandidateLedger(
        token_lists=token_lists, fvu=fvu, log_prob=log_prob,
        valid=valid, fit_status=fit_status, constants=constants,
        n_nodes=n_nodes, n_constants=n_constants, mdl=mdl, score=score,
        pareto_rank=pareto_rank, rank=rank, result_index=result_index,
        spelling=spelling, parent=parent,
    )
