"""The result of one :meth:`FlashANSR.fit`.

A fit over one problem yields a :class:`FitResult`: the score-sorted refined :class:`Candidate`s
(the ones that fitted) PLUS a :class:`CandidateLedger` -- the FULL generation pool joined with the
refined survivors and classified FIT_OK / FIT_FAILED / INVALID -- the ranking that ordered them and
the two phase times. The result is plain data: it owns no model objects (no refiner, no lambda), so
it pickles, streams and compares; evaluation and rendering go through the simplipy engine the
estimator binds to it (``FitResult.load(path, engine=...)`` rebinds one).
"""
from __future__ import annotations

import copy
import pickle
from dataclasses import dataclass, field, replace
from pathlib import Path
from typing import Any, Callable, Sequence

import numpy as np

from simplipy.utils import codify
from symbolic_data.token_ops import apply_variable_mapping

from flash_ansr.refine import fit_sort_key
from flash_ansr.scoring import PARETO_RANK_NOT_COMPUTED, RankingConfig, order_rows, resolve_ranking
from flash_ansr.utils.tensor_ops import pad_input_set

# Per-candidate fit outcome (a candidate generated by the model + put through constant refinement).
FIT_OK = 0        # refined successfully (finite fvu); carries fitted constants
FIT_FAILED = 1    # a VALID expression whose constant refinement did not converge
INVALID = 2       # not a valid expression (rejected before refinement)

RESULT_FORMAT_VERSION = 3


@dataclass
class Candidate:
    """One refined survivor (a generated expression that fitted). Plain data, rich, for interactive use."""

    raw_beam: list[int]                 # full beam ids -- the dedup-unique candidate identity
    expression: list[str]               # the candidate as the model stated it: spelled literals kept, refined sites as '<constant>'
    slots: list[int]                    # positions in `expression` the refiner fitted, in order of `constants`
    expression_prefix: list[str]        # constants substituted, x1..xN vars, raw PREFIX tokens (symbolic_data.token_ops.normalize_expression for canonical form)
    expression_infix: str               # human-readable prediction: constants substituted, vars MAPPED, INFIX str (== get_expression())
    skeleton_prefix: list[str]          # normalized skeleton (constants as placeholders)
    constants: list[float]              # best-fit constant values (REFINED by the optimizer), one per slot
    constants_emitted: list[float] | None    # what the MODEL predicted, before refinement
    log_prob: float
    score: float                        # the scalar ranking score ('mdl' / 'weighted'); nan under 'pareto'
    fvu: float
    n_nodes: int                        # TOKEN COUNT of the emitted expression (the `n_nodes` ranking metric)
    mu: float | None                    # simplipy complexity of the masked SKELETON -- the unit fit(complexity=) consumes
    mdl: float | None                   # simplipy mu of the REALIZED expression (constants substituted), milli-bits -- the RANKING currency; None if unpriceable
    constant_count: int
    pruned_variant: bool                # synthesized during constant-pruning (not from generation)
    pareto_rank: int                    # front index under 'pareto' (0 = non-dominated); -1 when ranked by a scalar score
    rank: int                           # position in the score-sorted candidate list (0 = the returned answer)
    spelling: str | None = None         # constant-ladder variant: which fitted constants were re-spelled how (``c0=/ 3 2;c2=0``); None for a fitted draw
    typed_frozen: int = 0               # PREDICTED literals kept verbatim in a typed position (pow exponent / rootn index); 0 on the shipped path
    typed_thaw: str | None = None       # a `freeze_then_free` duplicate: the typed token indices it re-fitted; None otherwise

    def render(self, *, return_prefix: bool = False, precision: int | None = None,
               variable_mapping: dict[str, str] | None = None, engine: Any = None) -> list[str] | str:
        """The candidate with its constants substituted, as prefix tokens or an infix string.

        ``precision`` rounds the substituted constants for DISPLAY (``None`` = the round-trip-exact
        ``repr``); ``variable_mapping`` renames ``x1..xN``. The infix form needs the ``engine``."""
        tokens = list(self.expression)
        values = np.asarray(self.constants, dtype=float)
        if precision is None:
            rendered = [repr(float(v)) for v in values.tolist()]
        else:
            rendered = [str(v) for v in np.round(values, precision).tolist()]
        for position, value in zip(self.slots, rendered):
            tokens[position] = value
        if variable_mapping:
            tokens = list(apply_variable_mapping(tokens, variable_mapping))
        if return_prefix:
            return tokens
        if engine is None:
            raise ValueError("rendering the infix form needs the simplipy engine (pass engine=, or use FitResult.get_expression)")
        return str(engine.prefix_to_infix(tokens))

    def evaluate(self, X: Any, engine: Any, n_variables: int | None = None) -> np.ndarray:
        """Evaluate the fitted expression on ``X`` (``(n_points, n_columns)``) -> ``(n_points, 1)``."""
        return evaluate_prefix(engine, self.expression_prefix, X, n_variables=n_variables)


_LAMBDA_CACHE: dict[tuple[int, tuple[str, ...], int], Callable[..., Any]] = {}


def evaluate_prefix(engine: Any, expression_prefix: Sequence[str], X: Any, *, n_variables: int | None = None) -> np.ndarray:
    """Evaluate a realized prefix expression (constants substituted, ``x1..xN``) on ``X`` through
    the engine's realizations. ``X`` is padded to ``n_variables`` columns (default: its own width)."""
    X_arr = np.asarray(X.detach().cpu().numpy() if hasattr(X, 'detach') else (X.values if hasattr(X, 'values') else X), dtype=np.float64)
    if X_arr.ndim == 1:
        X_arr = X_arr.reshape(-1, 1)
    width = int(n_variables) if n_variables is not None else int(X_arr.shape[1])
    if X_arr.shape[1] > width:
        X_arr = X_arr[:, :width]
    X_arr = pad_input_set(X_arr, width)
    key = (id(engine), tuple(map(str, expression_prefix)), width)
    fn = _LAMBDA_CACHE.get(key)
    if fn is None:
        realized = engine.operators_to_realizations(list(expression_prefix))
        code_string = engine.prefix_to_infix(realized, realization=True)
        code = codify(code_string=code_string, variables=[f'x{i + 1}' for i in range(width)])
        fn = engine.code_to_lambda(code)
        if len(_LAMBDA_CACHE) > 4096:
            _LAMBDA_CACHE.clear()
        _LAMBDA_CACHE[key] = fn
    y = fn(*X_arr.T)
    if not isinstance(y, np.ndarray):
        y = np.full((X_arr.shape[0], 1), y, dtype=np.float64)
    y = np.asarray(y, dtype=np.float64)
    if y.size == 1 and X_arr.shape[0] != 1:
        y = np.repeat(y.reshape(-1), X_arr.shape[0])
    return y.reshape(-1, 1)


@dataclass
class CandidateLedger:
    """The FULL generation pool U refined survivors, classified -- the lean columnar "all candidates"
    object. Holds NO model objects.

    The ranking columns (``n_nodes``, ``n_constants``, ``mdl``, ``score``, ``pareto_rank``, ``rank``)
    are copied from the refined result rows, never re-derived from the raw beam ids (which would
    need the tokenizer and the span mapper). Non-fitted rows carry nan / -1. ``rank`` is the
    position in the score-sorted candidate list, so an offline re-sort of the ledger can be checked
    against what the live run actually returned (rank 0)."""

    token_lists: list[list[int]]
    fvu: list[float]
    log_prob: list[float]
    valid: list[int]
    fit_status: list[int]               # FIT_OK / FIT_FAILED / INVALID
    constants: list[list[float]]
    n_nodes: list[int] = field(default_factory=list)          # -1 for non-fitted rows
    n_constants: list[int] = field(default_factory=list)      # -1 for non-fitted rows
    mdl: list[float] = field(default_factory=list)            # milli-bits; nan if unpriced / non-fitted
    score: list[float] = field(default_factory=list)          # nan for non-fitted rows and under 'pareto'
    pareto_rank: list[int] = field(default_factory=list)      # -1 unless ranked by 'pareto'
    rank: list[int] = field(default_factory=list)             # -1 for non-fitted rows
    result_index: list[int] = field(default_factory=list)     # index into FitResult.candidates; -1 if none
    spelling: list[str] = field(default_factory=list)        # constant-ladder record; '' for a fitted draw / non-fitted row
    parent: list[int] = field(default_factory=list)          # ledger row of the beam a ladder variant was re-spelled from; -1 otherwise

    def __len__(self) -> int:
        return len(self.token_lists)


@dataclass
class FitResult:
    """The result of one :meth:`FlashANSR.fit`: score-sorted refined candidates, the full ledger,
    the ranking that ordered them and the phase times. ``best`` is ``None`` when nothing fitted."""

    candidates: list[Candidate]         # FIT_OK survivors, score-sorted (best first)
    ledger: CandidateLedger             # full generation pool U refined, classified
    generation_time: float
    refinement_time: float
    ranking: RankingConfig              # the ranking that ordered `candidates`
    n_variables: int                    # the model's input width (X is padded to it for evaluation)
    variable_mapping: dict[str, str] = field(default_factory=dict)
    draws: int | None = None            # the search budget of the call
    engine: Any = field(default=None, repr=False, compare=False)   # the simplipy engine, for evaluation / rendering; not serialized

    @property
    def best(self) -> Candidate | None:
        return self.candidates[0] if self.candidates else None

    def _candidate(self, rank: int) -> Candidate:
        if not self.candidates:
            raise ValueError("no candidate fitted: the result is empty (see `ledger` for the pool)")
        return self.candidates[rank]

    def _need_engine(self) -> Any:
        if self.engine is None:
            raise ValueError("this FitResult carries no simplipy engine; pass engine= to FitResult.load or set `result.engine`")
        return self.engine

    def predict(self, X: Any, rank: int = 0) -> np.ndarray:
        """Evaluate the candidate at ``rank`` on ``X`` -> ``(n_points, 1)``."""
        return self._candidate(rank).evaluate(X, self._need_engine(), n_variables=self.n_variables)

    def get_expression(self, rank: int = 0, *, return_prefix: bool = False, precision: int | None = None,
                       map_variables: bool = True) -> list[str] | str:
        """The candidate at ``rank`` with its constants substituted, infix (default) or prefix."""
        c = self._candidate(rank)
        mapping = self.variable_mapping if map_variables else None
        if precision is None:
            if return_prefix:
                return list(apply_variable_mapping(list(c.expression_prefix), mapping)) if mapping else list(c.expression_prefix)
            if map_variables:
                return c.expression_infix
        return c.render(return_prefix=return_prefix, precision=precision, variable_mapping=mapping,
                        engine=None if return_prefix else self._need_engine())

    def rerank(self, ranking: RankingConfig | str | None = None, **knobs: Any) -> "FitResult":
        """A NEW result ordered under another ranking; this one is untouched.

        ``ranking`` is a :class:`RankingConfig`, a mode name (``'mdl'`` / ``'weighted'`` /
        ``'pareto'``) or ``None`` (this result's mode); ``knobs`` are that mode's
        (``mdl_strength``, ``weights``, ``metrics``, ``tie_break``), resolved exactly as at
        construction, so a knob of another mode raises rather than being ignored."""
        if isinstance(ranking, RankingConfig):
            if knobs:
                raise ValueError("pass either a RankingConfig or a mode plus its knobs, not both")
            cfg = ranking
        else:
            mode = self.ranking.mode if ranking is None else str(ranking)
            cfg = resolve_ranking(mode, **knobs)
        rows = [{'index': i, 'fvu': c.fvu, 'mdl': c.mdl, 'expression': list(c.expression), 'constant_count': c.constant_count,
                 'log_prob': c.log_prob, 'score': 0.0, 'pareto_rank': PARETO_RANK_NOT_COMPUTED} for i, c in enumerate(self.candidates)]
        ordered = order_rows(rows, cfg)
        new_rank_of = {row['index']: new_rank for new_rank, row in enumerate(ordered)}
        candidates = [replace(self.candidates[row['index']], score=float(row['score']), pareto_rank=int(row['pareto_rank']), rank=new_rank)
                      for new_rank, row in enumerate(ordered)]
        ledger = copy.deepcopy(self.ledger)
        for i, old in enumerate(ledger.result_index):
            if old >= 0:
                new_rank = new_rank_of[old]
                ledger.result_index[i] = new_rank
                ledger.rank[i] = new_rank
                ledger.score[i] = float(candidates[new_rank].score)
                ledger.pareto_rank[i] = int(candidates[new_rank].pareto_rank)
        return replace(self, candidates=candidates, ledger=ledger, ranking=cfg)

    def to_dataframe(self) -> "Any":
        import pandas as pd
        rows = [
            {
                "expression_infix": c.expression_infix,
                "expression_prefix": c.expression_prefix,
                "skeleton_prefix": c.skeleton_prefix,
                "constants": c.constants,
                "log_prob": c.log_prob,
                "score": c.score,
                "fvu": c.fvu,
                "n_nodes": c.n_nodes,
                "mu": c.mu,
                "mdl": c.mdl,
                "constant_count": c.constant_count,
                "pruned_variant": c.pruned_variant,
                "pareto_rank": c.pareto_rank,
                "rank": c.rank,
                "spelling": c.spelling,
                "typed_frozen": c.typed_frozen,
                "typed_thaw": c.typed_thaw,
            }
            for c in self.candidates
        ]
        return pd.DataFrame(rows)

    def save(self, path: str | Path) -> None:
        """Persist the result as plain data (no engine, no model objects)."""
        payload = {
            'format_version': RESULT_FORMAT_VERSION,
            'candidates': [c.__dict__ for c in self.candidates],
            'ledger': self.ledger.__dict__,
            'generation_time': self.generation_time,
            'refinement_time': self.refinement_time,
            'ranking': self.ranking.as_dict(),
            'n_variables': self.n_variables,
            'variable_mapping': dict(self.variable_mapping),
            'draws': self.draws,
        }
        with open(path, 'wb') as fh:
            pickle.dump(payload, fh)

    @classmethod
    def load(cls, path: str | Path, *, engine: Any = None) -> "FitResult":
        """Read a saved result; ``engine`` (a simplipy engine) enables ``predict`` / rendering."""
        with open(path, 'rb') as fh:
            payload = pickle.load(fh)
        version = int(payload.get('format_version', 0))
        if version != RESULT_FORMAT_VERSION:
            raise ValueError(f"FitResult payload format {version} is not the supported format {RESULT_FORMAT_VERSION}")
        return cls(
            candidates=[Candidate(**c) for c in payload['candidates']],
            ledger=CandidateLedger(**payload['ledger']),
            generation_time=float(payload['generation_time']),
            refinement_time=float(payload['refinement_time']),
            ranking=RankingConfig.from_dict(payload['ranking']),
            n_variables=int(payload['n_variables']),
            variable_mapping=dict(payload.get('variable_mapping') or {}),
            draws=payload.get('draws'),
            engine=engine,
        )

    def __getstate__(self) -> dict[str, Any]:
        state = dict(self.__dict__)
        state['engine'] = None
        return state


def _best_constants(result: dict) -> list[float]:
    """Best-fit constants of a refined result (``fits[0][0]``), else empty."""
    fits = result.get("fits") or []
    if not fits:
        return []
    # fit_sort_key, not a bare loss key: `min` over a list containing NaN returns whatever
    # happens to be first (NaN loses every comparison), which would publish a DIVERGENT
    # restart's constants on Candidate.constants while a finite fit sat in the same list.
    best = min(fits, key=fit_sort_key)             # (constants, cov, loss) -> lowest FINITE loss
    arr = np.asarray(best[0], dtype=np.float64).ravel()
    return arr.tolist()


def build_candidate_ledger(
    raw_beams: Sequence[Sequence[int]],
    log_probs: Sequence[float],
    results: Sequence[dict],
    *,
    decode_expr: Callable[[list[int]], list[str] | None] | None = None,
    is_valid: Callable[[list[str]], bool] | None = None,
) -> CandidateLedger:
    """Join the FULL generation pool with the refined results into a classified columnar ledger.

    ``raw_beams`` / ``log_probs`` are the unique generation pool; ``results`` are the refined
    survivors (each dict carries ``raw_beam`` -- the dedup-unique identity -- plus ``fvu``,
    ``log_prob``, ``fits``). A gen candidate present in ``results`` is FIT_OK; one ABSENT is
    not-fitted and split FIT_FAILED vs INVALID by re-running validity ONLY on that (small) subset
    via ``decode_expr`` + ``is_valid`` (so the bulk pays no per-candidate cost). Pruned variants
    (present in ``results``, synthesized in refinement, absent from the gen pool) ride along FIT_OK.
    The token column is the raw beam ids (decode offline if needed).
    """
    def _key(raw_beam: Sequence[Any], spelling: Any, typed_thaw: Any = None) -> tuple:
        return (tuple(int(t) for t in raw_beam), str(spelling or ""), str(typed_thaw or ""))

    # Keyed on the beam AND what was done to it: a re-spelled variant (constant ladder) and a
    # typed-span duplicate (`refiner_typed_spans='freeze_then_free'`, which refits the candidate with
    # its predicted exponent thawed) both share their parent's beam and are rows of their own. Keying
    # on the beam alone made a duplicate collide with its parent, so the ledger came back SHORTER
    # than the candidate list it is supposed to cover.
    fitted: dict[tuple, tuple[int, dict]] = {
        _key(r["raw_beam"], r.get("spelling"), r.get("typed_thaw")): (i, r) for i, r in enumerate(results)}
    # a variant that REPLACED its parent (a tie in score) is the fitted result of that beam
    for i, r in enumerate(results):
        if r.get("spelling") and r.get("replaces_parent"):
            fitted.setdefault(_key(r["raw_beam"], "", r.get("typed_thaw")), (i, r))

    token_lists: list[list[int]] = []
    fvu: list[float] = []
    log_prob: list[float] = []
    valid: list[int] = []
    fit_status: list[int] = []
    constants: list[list[float]] = []
    n_nodes: list[int] = []
    n_constants: list[int] = []
    mdl: list[float] = []
    score: list[float] = []
    pareto_rank: list[int] = []
    rank: list[int] = []
    result_index: list[int] = []
    spelling: list[str] = []
    parent: list[int] = []
    seen: set[tuple] = set()

    def _fitted_row(i: int, r: dict) -> None:
        fvu.append(float(r["fvu"]))
        valid.append(1)
        fit_status.append(FIT_OK)
        constants.append(_best_constants(r))
        n_nodes.append(len(r.get("expression") or []))
        cc = r.get("constant_count")
        n_constants.append(-1 if cc is None else int(cc))
        m = r.get("mdl")
        mdl.append(float("nan") if m is None else float(m))
        sc = r.get("score")
        score.append(float("nan") if sc is None else float(sc))
        pareto_rank.append(int(r.get("pareto_rank", PARETO_RANK_NOT_COMPUTED)))
        rank.append(i)              # `results` arrive score-sorted: the list position IS the rank
        result_index.append(i)
        spelling.append(str(r.get("spelling") or ""))
        parent.append(-1)

    def _unfitted_row(v: bool) -> None:
        fvu.append(float("nan"))
        constants.append([])
        valid.append(1 if v else 0)
        fit_status.append(FIT_FAILED if v else INVALID)
        n_nodes.append(-1)
        n_constants.append(-1)
        mdl.append(float("nan"))
        score.append(float("nan"))
        pareto_rank.append(PARETO_RANK_NOT_COMPUTED)
        rank.append(-1)
        result_index.append(-1)
        spelling.append("")
        parent.append(-1)

    for rb, lp in zip(raw_beams, log_probs):
        rb_list = [int(t) for t in rb]
        key = _key(rb_list, "")
        seen.add(key)
        token_lists.append(rb_list)
        hit = fitted.get(key)
        if hit is not None:
            i, r = hit
            log_prob.append(float(r.get("log_prob", lp)))
            _fitted_row(i, r)
            continue
        v = True
        if decode_expr is not None and is_valid is not None:
            try:
                toks = decode_expr(rb_list)
                v = bool(is_valid(toks)) if toks is not None else False
            except Exception:  # noqa: BLE001
                v = False
        log_prob.append(float(lp))
        _unfitted_row(v)

    for i, pruned in enumerate(results):
        key = _key(pruned["raw_beam"], pruned.get("spelling"), pruned.get("typed_thaw"))
        if key in seen or (pruned.get("spelling") and pruned.get("replaces_parent")
                           and _key(pruned["raw_beam"], "", pruned.get("typed_thaw")) in seen):
            continue
        seen.add(key)
        token_lists.append(list(key[0]))
        log_prob.append(float(pruned.get("log_prob", float("nan"))))
        _fitted_row(i, pruned)

    # a ladder variant points at the row of the beam it was re-spelled from
    row_of: dict[tuple, int] = {}
    for row, (rb, sp) in enumerate(zip(token_lists, spelling)):
        if not sp:
            row_of.setdefault(tuple(rb), row)
    for row, (rb, sp) in enumerate(zip(token_lists, spelling)):
        if sp:
            parent[row] = row_of.get(tuple(rb), -1)
    return CandidateLedger(
        token_lists=token_lists, fvu=fvu, log_prob=log_prob,
        valid=valid, fit_status=fit_status, constants=constants,
        n_nodes=n_nodes, n_constants=n_constants, mdl=mdl, score=score,
        pareto_rank=pareto_rank, rank=rank, result_index=result_index,
        spelling=spelling, parent=parent,
    )
