"""Public inference result types for :meth:`FlashANSR.infer`.

A single inference over one problem yields an :class:`InferenceResult`: the score-sorted refined
:class:`Candidate`s (the ones that fitted), PLUS a :class:`CandidateLedger` -- the FULL generation
pool joined with the refined survivors and classified FIT_OK / FIT_FAILED / INVALID. The ledger is
the lean, columnar "all candidates" object a benchmark's save-all tier persists; it owns no model
objects (no refiner / no lambda), so it streams and serializes cheaply.

This replaces a consumer scraping ``model._results`` / ``predict(nth_best_beam=...)`` after ``fit``:
the candidate set + every field a benchmark stores is returned directly.
"""
from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any, Callable, Sequence

import numpy as np

# Per-candidate fit outcome (a candidate generated by the model + put through constant refinement).
FIT_OK = 0        # refined successfully (finite fvu); carries fitted constants
FIT_FAILED = 1    # a VALID expression whose constant refinement did not converge
INVALID = 2       # not a valid expression (rejected before refinement)


@dataclass
class Candidate:
    """One refined survivor (a generated expression that fitted). Rich, for interactive use."""

    raw_beam: list[int]                 # full beam ids -- the dedup-unique candidate identity
    expression: list[str]               # decoded skeleton tokens (constants as placeholders)
    expression_prefix: list[str]        # constants substituted, x1..xN vars, raw PREFIX tokens (simplipy.normalize_expression for canonical form)
    expression_infix: str               # human-readable prediction: constants substituted, vars MAPPED, INFIX str (== get_expression(map_variables=True))
    skeleton_prefix: list[str]          # normalized skeleton (constants as placeholders)
    constants: list[float]              # best-fit constant values
    log_prob: float
    score: float
    fvu: float
    complexity: int
    constant_count: int
    pruned_variant: bool                # synthesized during constant-pruning (not from generation)
    y_pred: np.ndarray | None = None        # on support X -- populated only for the top_k (opt-in; OOM otherwise)
    y_pred_val: np.ndarray | None = None    # on validation X -- top_k only


@dataclass
class CandidateLedger:
    """The FULL generation pool U refined survivors, classified -- the lean columnar "all candidates"
    object (tokens + fvu + log_prob + valid + fit_status + best-constants). Holds NO model objects."""

    token_lists: list[list[int]]
    fvu: list[float]
    log_prob: list[float]
    valid: list[int]
    fit_status: list[int]               # FIT_OK / FIT_FAILED / INVALID
    constants: list[list[float]]

    def __len__(self) -> int:
        return len(self.token_lists)


@dataclass
class InferenceResult:
    """The result of one :meth:`FlashANSR.infer`: score-sorted refined candidates + the full ledger."""

    candidates: list[Candidate]         # FIT_OK survivors, score-sorted (best first)
    ledger: CandidateLedger             # full generation pool U refined, classified
    generation_time: float
    refinement_time: float
    variable_mapping: dict[str, str] = field(default_factory=dict)

    @property
    def best(self) -> Candidate | None:
        return self.candidates[0] if self.candidates else None

    def to_dataframe(self) -> "Any":
        import pandas as pd
        rows = [
            {
                "expression_infix": c.expression_infix,
                "expression_prefix": c.expression_prefix,
                "skeleton_prefix": c.skeleton_prefix,
                "constants": c.constants,
                "log_prob": c.log_prob,
                "score": c.score,
                "fvu": c.fvu,
                "complexity": c.complexity,
                "constant_count": c.constant_count,
                "pruned_variant": c.pruned_variant,
            }
            for c in self.candidates
        ]
        return pd.DataFrame(rows)


def _best_constants(result: dict) -> list[float]:
    """Best-fit constants of a refined result (``fits[0][0]``), else empty."""
    fits = result.get("fits") or []
    if not fits:
        return []
    best = min(fits, key=lambda tpl: tpl[2])      # (constants, cov, loss) -> lowest loss
    arr = np.asarray(best[0], dtype=np.float64).ravel()
    return arr.tolist()


def build_candidate_ledger(
    raw_beams: Sequence[Sequence[int]],
    log_probs: Sequence[float],
    results: Sequence[dict],
    *,
    decode_expr: Callable[[list[int]], list[str] | None] | None = None,
    is_valid: Callable[[list[str]], bool] | None = None,
) -> CandidateLedger:
    """Join the FULL generation pool with the refined results into a classified columnar ledger.

    ``raw_beams`` / ``log_probs`` are the unique generation pool; ``results`` are the refined
    survivors (each dict carries ``raw_beam`` -- the dedup-unique identity -- plus ``fvu``,
    ``log_prob``, ``fits``). A gen candidate present in ``results`` is FIT_OK; one ABSENT is
    not-fitted and split FIT_FAILED vs INVALID by re-running validity ONLY on that (small) subset
    via ``decode_expr`` + ``is_valid`` (so the bulk pays no per-candidate cost). Pruned variants
    (present in ``results``, synthesized in refinement, absent from the gen pool) ride along FIT_OK.
    The token column is the raw beam ids (decode offline if needed).
    """
    fitted: dict[tuple, dict] = {tuple(int(t) for t in r["raw_beam"]): r for r in results}

    token_lists: list[list[int]] = []
    fvu: list[float] = []
    log_prob: list[float] = []
    valid: list[int] = []
    fit_status: list[int] = []
    constants: list[list[float]] = []
    seen: set[tuple] = set()

    for rb, lp in zip(raw_beams, log_probs):
        rb_list = [int(t) for t in rb]
        key = tuple(rb_list)
        seen.add(key)
        token_lists.append(rb_list)
        hit = fitted.get(key)
        if hit is not None:
            fvu.append(float(hit["fvu"]))
            log_prob.append(float(hit.get("log_prob", lp)))
            valid.append(1)
            fit_status.append(FIT_OK)
            constants.append(_best_constants(hit))
            continue
        v = True
        if decode_expr is not None and is_valid is not None:
            try:
                toks = decode_expr(rb_list)
                v = bool(is_valid(toks)) if toks is not None else False
            except Exception:  # noqa: BLE001
                v = False
        fvu.append(float("nan"))
        log_prob.append(float(lp))
        constants.append([])
        valid.append(1 if v else 0)
        fit_status.append(FIT_FAILED if v else INVALID)

    for pruned in results:
        key = tuple(int(t) for t in pruned["raw_beam"])
        if key in seen:
            continue
        seen.add(key)
        token_lists.append(list(key))
        fvu.append(float(pruned["fvu"]))
        log_prob.append(float(pruned.get("log_prob", float("nan"))))
        valid.append(1)
        fit_status.append(FIT_OK)
        constants.append(_best_constants(pruned))

    return CandidateLedger(
        token_lists=token_lists, fvu=fvu, log_prob=log_prob,
        valid=valid, fit_status=fit_status, constants=constants,
    )
