encoder_max_n_variables: 4  # includes the dependent variable
size: 1024

pre_encoder_input_type: "ieee-754"
pre_encoder_support_nan: False

encoder: "SetTransformer"
encoder_kwargs:
  hidden_size: 1024
  n_enc_isab: 12
  n_dec_sab: 6
  n_induce: 384
  n_heads: 16
  layer_norm: False
  n_seeds: 384

decoder_n_heads: 16
decoder_ff_size: 1024
decoder_dropout: 0.1
decoder_n_layers: 12

learnable_positional_embeddings: false
max_input_length: null

expression_space: './expression_space.yaml'