model: ./nsr.yaml

optimizer:
  name: AdamWScheduleFree
  kwargs:
    lr: 0.0001
    weight_decay: 0.01

lr_scheduler: null

batch_size: 128

train_dataset: ./dataset_train.yaml
val_dataset: "./dataset_val.yaml"
val_batch_size: 128
val_size: 100_000

numeric_prediction_loss_weight: 0

steps: 1_500_000
device: cuda