encoder_max_n_variables: 12  # includes the dependent variable

pre_encoder_input_type: "ieee-754-32"
pre_encoder_support_nan: False

encoder: "SetTransformer"
encoder_kwargs:
  hidden_size: 512
  n_enc_isab: 6
  n_dec_sab: 4
  n_induce: 64
  n_heads: 8
  n_seeds: 64
  clean_path: True

size: 512
decoder_n_heads: 8
decoder_ff_size: 512
decoder_dropout: 0.1
decoder_n_layers: 7

learnable_positional_embeddings: False
max_input_length: null
support_numeric_tokens: True

expression_space: './expression_space.yaml'