model: ./nsr.yaml

optimizer:
  name: AdamW
  kwargs:
    lr: 1  # Will be multiplied by scheduler
    weight_decay: 0.001
    amsgrad: True

lr_scheduler:
  name: WarmupLinearAnnealing
  kwargs:
    min_lr: 0
    max_lr: 1e-4
    warmup_steps: 10_000
    total_steps: 15_000_000

batch_size: 128

train_dataset: ./dataset_train.yaml
val_dataset: "./dataset_val.yaml"
val_batch_size: 128
val_size: 100_000

numeric_prediction_loss_weight: 0

steps: 15_000_000
device: cuda