encoder_max_n_variables: 4  # includes the dependent variable

pre_encoder_input_type: "ieee-754"
pre_encoder_support_nan: False

encoder: "SetTransformer"
encoder_kwargs:
  hidden_size: 256
  n_enc_isab: 16
  n_dec_sab: 8
  n_induce: 64
  n_heads: 4
  layer_norm: False
  n_seeds: 64

size: 256
decoder_n_heads: 4
decoder_ff_size: 256
decoder_dropout: 0.1
decoder_n_layers: 24

learnable_positional_embeddings: False
max_input_length: null

expression_space: './expression_space.yaml'