encoder_max_n_variables: 4  # includes the dependent variable
size: 512

pre_encoder_input_type: "ieee-754"
pre_encoder_support_nan: False

encoder: "SetTransformer2"
encoder_kwargs:
  hidden_size: 512
  n_enc_isab: 5
  n_dec_sab: 2
  n_induce: 64
  n_heads: 8
  set_norm_ko: True
  n_seeds: 64

decoder_n_heads: 8
decoder_ff_size: 512
decoder_dropout: 0.1
decoder_n_layers: 5

learnable_positional_embeddings: False
max_input_length: null

expression_space: './expression_space.yaml'